# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='hostel.bed'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='previous_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_allocations', to='hostel.bed'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocation', to='students.student'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hostel.hostelallocation'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelbuilding',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelbuilding',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.hostelallocation'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelfeepayment',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='hostel.hostelallocation'),
        ),
        migrations.AddField(
            model_name='hostelfeepayment',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_fee_structures', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='hostelfeepayment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='hostel.hostelfeestructure'),
        ),
        migrations.AddField(
            model_name='hostelgatepass',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_gate_passes', to='hostel.hostelallocation'),
        ),
        migrations.AddField(
            model_name='hostelgatepass',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hostel_gate_passes', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='hostelgatepass',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='hostel.hostelbuilding'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messattendance',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_menus', to='hostel.hostelbuilding'),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messregistration',
            name='allocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mess_registration', to='hostel.hostelallocation'),
        ),
        migrations.AddField(
            model_name='messregistration',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messattendance',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hostel.messregistration'),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostelbuilding'),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='hostel.room'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.room'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostel.room'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelattendance',
            unique_together={('allocation', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelfeestructure',
            unique_together={('academic_year', 'room_type')},
        ),
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together={('building', 'week_start_date', 'day_of_week', 'meal_type')},
        ),
        migrations.AlterUniqueTogether(
            name='messattendance',
            unique_together={('registration', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
