# Generated by Django 5.2.9 on 2026-01-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
    ]
