# Generated by Django 5.1.4 on 2025-12-27 20:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='School/Institution name', max_length=255)),
                ('subdomain', models.SlugField(help_text="Unique subdomain (e.g., 'myschool' for myschool.nucleiq.com)", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')])),
                ('schema_name', models.CharField(editable=False, help_text='Database schema name (auto-generated from subdomain)', max_length=63, unique=True)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', help_text='Subscription plan', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this tenant is active')),
                ('admin_email', models.EmailField(help_text='Primary admin email for this tenant', max_length=254)),
                ('admin_phone', models.CharField(blank=True, help_text='Primary admin phone number', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial period ends', null=True)),
                ('subscription_starts_at', models.DateTimeField(blank=True, help_text='When the paid subscription started', null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, help_text='When the subscription expires', null=True)),
                ('max_students', models.PositiveIntegerField(default=100, help_text='Maximum number of students allowed')),
                ('max_staff', models.PositiveIntegerField(default=20, help_text='Maximum number of staff members allowed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tenant metadata')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to the school logo', max_length=500)),
                ('favicon_url', models.URLField(blank=True, help_text='URL to the favicon', max_length=500)),
                ('login_background_url', models.URLField(blank=True, help_text='URL to the login page background image', max_length=500)),
                ('email_header_image', models.URLField(blank=True, help_text='URL to the email header image', max_length=500)),
                ('primary_color', models.CharField(default='#1976D2', help_text='Primary brand color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g., #1976D2)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_color', models.CharField(default='#424242', help_text='Secondary brand color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code', regex='^#[0-9A-Fa-f]{6}$')])),
                ('sidebar_color', models.CharField(default='#263238', help_text='Sidebar background color (hex code)', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code', regex='^#[0-9A-Fa-f]{6}$')])),
                ('font_family', models.CharField(default='Inter, sans-serif', help_text='Primary font family', max_length=100)),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of gallery image URLs (JSON array)')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for advanced styling')),
                ('tenant', models.OneToOneField(help_text='Tenant this branding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Branding',
                'verbose_name_plural': 'Tenant Brandings',
                'db_table': 'tenant_branding',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('domain', models.CharField(help_text='Custom domain (e.g., portal.myschool.com)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$')])),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary domain for the tenant')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this domain is active')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the domain was verified', null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'tenant_domains',
                'ordering': ['-is_primary', 'domain'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant', 'is_primary'), name='unique_primary_domain_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Academic year name (e.g., '2024-2025')", max_length=50)),
                ('start_date', models.DateField(help_text='Start date of the academic year')),
                ('end_date', models.DateField(help_text='End date of the academic year')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this is the currently active academic year')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this academic year is locked (for past years)')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('tenant', models.ForeignKey(help_text='Tenant this academic year belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_academic_year_name_per_tenant'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'is_active'), name='unique_active_academic_year_per_tenant'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date')],
            },
        ),
    ]
