# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher for this subject-grade combination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Head of department (staff member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this grade belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='tenants.department'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='grade_level',
            field=models.ForeignKey(help_text='Grade level', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Class teacher for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='grade_level',
            field=models.ForeignKey(help_text='Grade level this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this holiday belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this grade level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this academic year belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='tenant',
            field=models.OneToOneField(help_text='Tenant this branding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tenant',
            field=models.OneToOneField(help_text='Tenant these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term_number'), name='unique_term_number_per_year'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year', 'is_active'), name='unique_active_term_per_year'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='term_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_subject_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_subject_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('grade_level', 'name'), name='unique_section_name_per_grade'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='holidays_tenant__6f5802_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['academic_year'], name='holidays_academi_2aa612_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradelevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_grade_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='gradelevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'display_order'), name='unique_grade_order_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant', 'is_primary'), name='unique_primary_domain_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_department_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_department_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade_level', 'subject'), name='unique_subject_per_grade_per_year'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_academic_year_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'is_active'), name='unique_active_academic_year_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date'),
        ),
    ]
