# Generated by Django 5.1.4 on 2025-12-28 00:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_enrollment_open',
            field=models.BooleanField(default=False, help_text='Whether enrollment/admission is open for this year'),
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Term name (e.g., 'Term 1', 'Semester 1', 'Q1')", max_length=50)),
                ('term_type', models.CharField(choices=[('TERM', 'Term'), ('SEMESTER', 'Semester'), ('QUARTER', 'Quarter'), ('TRIMESTER', 'Trimester')], default='TERM', help_text='Type of term', max_length=20)),
                ('term_number', models.IntegerField(help_text='Sequential number (1, 2, 3, etc.)')),
                ('start_date', models.DateField(help_text='Start date of the term')),
                ('end_date', models.DateField(help_text='End date of the term')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this is the currently active term')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('academic_year', models.ForeignKey(help_text='Academic year this term belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tenants.academicyear')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'db_table': 'academic_terms',
                'ordering': ['academic_year', 'term_number'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'term_number'), name='unique_term_number_per_year'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('academic_year', 'is_active'), name='unique_active_term_per_year'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='term_end_date_after_start_date')],
            },
        ),
    ]
