# Generated by Django 5.2.9 on 2026-01-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='admin_session_timeout_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Django admin session timeout in minutes. Minimum: 5, Maximum: 1440 (24 hours)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='refresh_timeout_days',
            field=models.PositiveIntegerField(default=7, help_text='Refresh token lifetime in days (how long users stay logged in). Minimum: 1, Maximum: 30'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Session timeout in minutes (JWT access token lifetime). Minimum: 5, Maximum: 1440 (24 hours)'),
        ),
    ]
