# Generated by Django 5.1.4 on 2025-12-28 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_academicyear_is_enrollment_open_academicterm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Department name (e.g., 'Primary', 'High School')", max_length=100)),
                ('code', models.CharField(help_text="Short code (e.g., 'PRI', 'HS')", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is active')),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('head_of_department', models.ForeignKey(blank=True, help_text='Head of department (staff member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Grade name (e.g., 'Class 1', 'Grade 10')", max_length=50)),
                ('short_name', models.CharField(help_text="Short name (e.g., '1', '10', 'KG')", max_length=20)),
                ('display_order', models.IntegerField(help_text='Display order (1, 2, 3... for Class 1, 2, 3...)')),
                ('description', models.TextField(blank=True, help_text='Grade description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this grade is active')),
                ('department', models.ForeignKey(blank=True, help_text='Department this grade belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='tenants.department')),
                ('tenant', models.ForeignKey(help_text='Tenant this grade level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'db_table': 'grade_levels',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Section name (e.g., 'A', 'Red', 'Alpha')", max_length=50)),
                ('capacity', models.IntegerField(default=40, help_text='Maximum number of students allowed')),
                ('room_number', models.CharField(blank=True, help_text='Classroom/room number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active')),
                ('display_order', models.IntegerField(default=0, help_text='Display order within grade')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Class teacher for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_sections', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(help_text='Grade level this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.gradelevel')),
                ('tenant', models.ForeignKey(help_text='Tenant this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
                'ordering': ['grade_level', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Subject name (e.g., 'Mathematics', 'Physics')", max_length=100)),
                ('code', models.CharField(help_text="Subject code (e.g., 'MATH', 'PHY')", max_length=20)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('BOTH', 'Theory & Practical')], default='THEORY', help_text='Type of subject', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Subject description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is active')),
                ('display_order', models.IntegerField(default=0, help_text='Display order')),
                ('tenant', models.ForeignKey(help_text='Tenant this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this subject is mandatory for this grade')),
                ('is_elective', models.BooleanField(default=False, help_text='Whether this is an elective subject')),
                ('weekly_periods', models.IntegerField(default=5, help_text='Number of periods per week')),
                ('total_marks', models.IntegerField(default=100, help_text='Total marks for this subject')),
                ('passing_marks', models.IntegerField(default=40, help_text='Minimum passing marks')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in report cards')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this mapping', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.academicyear')),
                ('teacher', models.ForeignKey(blank=True, help_text='Primary teacher for this subject-grade combination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.tenant')),
                ('grade_level', models.ForeignKey(help_text='Grade level', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.gradelevel')),
                ('subject', models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='tenants.subject')),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'db_table': 'class_subjects',
                'ordering': ['grade_level', 'display_order', 'subject'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_department_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_department_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='gradelevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_grade_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='gradelevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'display_order'), name='unique_grade_order_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('grade_level', 'name'), name='unique_section_name_per_grade'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_subject_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_subject_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade_level', 'subject'), name='unique_subject_per_grade_per_year'),
        ),
    ]
