# Generated by Django 5.2.9 on 2026-01-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_session_timeout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled module keys for this tenant. Basic modules: dashboard, settings, users, students'),
        ),
    ]
