# Generated by Django 5.1.4 on 2026-01-03 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Holiday name (e.g., 'Independence Day', 'Summer Break')", max_length=200)),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('SCHOOL', 'School Holiday'), ('VACATION', 'Vacation/Break'), ('EXAM', 'Exam Day'), ('EVENT', 'School Event'), ('OTHER', 'Other')], default='PUBLIC', help_text='Type of holiday', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of holiday')),
                ('end_date', models.DateField(help_text='End date of holiday (same as start_date for single day)')),
                ('description', models.TextField(blank=True, help_text='Additional description or notes')),
                ('is_attendance_blocked', models.BooleanField(default=True, help_text='Whether attendance marking is blocked on this holiday')),
                ('applies_to_students', models.BooleanField(default=True, help_text='Whether this holiday applies to students')),
                ('applies_to_staff', models.BooleanField(default=True, help_text='Whether this holiday applies to staff')),
                ('color', models.CharField(default='#FF5722', help_text='Color for calendar display (hex code)', max_length=7)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Academic year (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(help_text='Tenant this holiday belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['tenant', 'start_date', 'end_date'], name='holidays_tenant__6f5802_idx'), models.Index(fields=['academic_year'], name='holidays_academi_2aa612_idx')],
            },
        ),
    ]
