# Generated by Django 5.1.4 on 2026-01-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_enabled_modules_to_tenant'),
        ('tenants', '0004_update_icon_set_choices'),
    ]

    operations = [
    ]
