# Generated by Django 5.1.4 on 2026-01-03 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('academic_year_format', models.CharField(default='YYYY-YYYY', help_text="Format for academic year display (e.g., '2024-2025')", max_length=50)),
                ('term_system', models.CharField(choices=[('TERM', 'Term System'), ('SEMESTER', 'Semester System'), ('QUARTER', 'Quarter System'), ('TRIMESTER', 'Trimester System')], default='TERM', help_text='Academic term system', max_length=20)),
                ('grading_system', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('GPA', 'GPA (4.0 Scale)'), ('LETTER', 'Letter Grades'), ('CGPA', 'CGPA (10.0 Scale)')], default='PERCENTAGE', help_text='Grading system used', max_length=20)),
                ('fee_currency', models.CharField(default='INR', help_text='Currency code (ISO 4217)', max_length=3)),
                ('fee_currency_symbol', models.CharField(default='₹', help_text='Currency symbol', max_length=5)),
                ('late_fee_enabled', models.BooleanField(default=True, help_text='Whether late fees are enabled')),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Late fee amount', max_digits=10)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Late fee as percentage of total', max_digits=5)),
                ('grace_period_days', models.IntegerField(default=7, help_text='Grace period before late fee applies (days)')),
                ('attendance_marking_time', models.TimeField(blank=True, help_text='Default time for marking attendance', null=True)),
                ('attendance_lock_days', models.IntegerField(default=7, help_text='Days after which attendance cannot be modified')),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum required attendance percentage', max_digits=5)),
                ('late_arrival_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after which arrival is considered late')),
                ('result_publish_delay_days', models.IntegerField(default=7, help_text='Days to wait before publishing results')),
                ('allow_online_exams', models.BooleanField(default=True, help_text='Whether online exams are enabled')),
                ('exam_proctoring_enabled', models.BooleanField(default=False, help_text='Whether exam proctoring is enabled')),
                ('email_enabled', models.BooleanField(default=True, help_text='Whether email notifications are enabled')),
                ('smtp_host', models.CharField(blank=True, help_text='SMTP server host', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP username', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP password (encrypted)', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS for SMTP')),
                ('from_email', models.EmailField(blank=True, help_text="Default 'from' email address", max_length=254)),
                ('sms_enabled', models.BooleanField(default=False, help_text='Whether SMS notifications are enabled')),
                ('sms_provider', models.CharField(choices=[('TWILIO', 'Twilio'), ('MSG91', 'MSG91'), ('AWS_SNS', 'AWS SNS'), ('CUSTOM', 'Custom')], default='TWILIO', help_text='SMS provider', max_length=50)),
                ('sms_api_key', models.CharField(blank=True, help_text='SMS API key (encrypted)', max_length=255)),
                ('sms_sender_id', models.CharField(blank=True, help_text='SMS sender ID', max_length=20)),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text='Whether WhatsApp notifications are enabled')),
                ('whatsapp_api_key', models.CharField(blank=True, help_text='WhatsApp Business API key', max_length=255)),
                ('password_min_length', models.IntegerField(default=8, help_text='Minimum password length')),
                ('password_require_uppercase', models.BooleanField(default=True, help_text='Require uppercase letters in password')),
                ('password_require_lowercase', models.BooleanField(default=True, help_text='Require lowercase letters in password')),
                ('password_require_numbers', models.BooleanField(default=True, help_text='Require numbers in password')),
                ('password_require_special', models.BooleanField(default=False, help_text='Require special characters in password')),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Maximum failed login attempts before lockout')),
                ('lockout_duration_minutes', models.IntegerField(default=30, help_text='Account lockout duration in minutes')),
                ('two_factor_auth_required', models.BooleanField(default=False, help_text='Whether 2FA is required for all users')),
                ('auto_backup_enabled', models.BooleanField(default=True, help_text='Whether automatic backups are enabled')),
                ('backup_frequency_days', models.IntegerField(default=1, help_text='Backup frequency in days')),
                ('backup_retention_days', models.IntegerField(default=30, help_text='Backup retention period in days')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Whether maintenance mode is active')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message to display during maintenance')),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Additional custom settings')),
                ('tenant', models.OneToOneField(help_text='Tenant these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
                'db_table': 'tenant_settings',
            },
        ),
    ]
