# Generated by Django 5.2.9 on 2026-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='admission_number_format',
            field=models.CharField(default='ADM{YEAR}{SEQUENCE:04d}', help_text="Format for admission number (e.g., 'ADM{YEAR}{SEQUENCE:04d}' -> ADM20240001)", max_length=100),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='admission_number_prefix',
            field=models.CharField(blank=True, default='ADM', help_text='Prefix for admission numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='admission_number_sequence',
            field=models.IntegerField(default=1, help_text='Current sequence number for admission numbers'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='auto_generate_admission_number',
            field=models.BooleanField(default=False, help_text='Whether to auto-generate admission numbers'),
        ),
    ]
