# Generated by Django 5.2.9 on 2026-01-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_student_ids_and_admission_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='receipt_copies',
            field=models.IntegerField(choices=[(1, 'Single Copy'), (2, 'Two Copies'), (3, 'Three Copies')], default=3, help_text='Number of receipt copies to print on a single A4 page'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='receipt_footer_text',
            field=models.TextField(blank=True, default='This is a computer generated receipt.', help_text='Custom footer text for fee receipts'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='school_address',
            field=models.TextField(blank=True, help_text='School address for documents and receipts'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='school_email',
            field=models.EmailField(blank=True, help_text='School email for documents', max_length=254),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='school_name',
            field=models.CharField(blank=True, help_text='School name for documents and receipts', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='school_phone',
            field=models.CharField(blank=True, help_text='School phone number for documents', max_length=50),
        ),
    ]
