# Generated by Django 5.2.9 on 2026-03-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_add_api_versioning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='auto_mark_absent_time',
            field=models.TimeField(default='10:00:00', help_text='Time at which auto-absent marking runs'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='enable_auto_mark_absent',
            field=models.BooleanField(default=False, help_text='Automatically mark staff and students as absent if attendance is not marked'),
        ),
    ]
