# Generated by Django 5.2.9 on 2026-01-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_audit_log_and_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='icon_theme',
            field=models.CharField(choices=[('modern_gradient', 'Modern Gradient'), ('minimal_outline', 'Minimal Outline'), ('duotone', 'Duotone'), ('retro_flat', 'Retro Flat'), ('neon_glow', 'Neon Glow'), ('classic_solid', 'Classic Solid')], default='modern_gradient', help_text='Icon and UI theme style for the tenant', max_length=30),
        ),
    ]
