# Generated by Django 5.2.9 on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_icon_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='icon_set',
            field=models.CharField(choices=[('lucide', 'Modern Line'), ('heroicons_outline', 'Heroicons Outline'), ('heroicons_solid', 'Heroicons Solid'), ('phosphor_regular', 'Phosphor Regular'), ('phosphor_bold', 'Phosphor Bold'), ('phosphor_fill', 'Phosphor Fill'), ('tabler', 'Tabler Icons'), ('material_outlined', 'Material Outlined')], default='lucide', help_text='Icon library set for the tenant', max_length=30),
        ),
    ]