# Generated by Django 5.1.4 on 2025-12-27 21:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('admission_number', models.CharField(db_index=True, help_text='Unique admission number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('current_class', models.CharField(help_text='e.g., Class 10A', max_length=50)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('admission_date', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=20)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=20)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('family_id', models.CharField(blank=True, db_index=True, help_text='Unique family identifier for sibling linking', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['admission_number'],
                'indexes': [models.Index(fields=['admission_number'], name='students_admissi_664d58_idx'), models.Index(fields=['family_id'], name='students_family__44d5e4_idx'), models.Index(fields=['current_class', 'section'], name='students_current_bec9d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('REPORT_CARD', 'Report Card'), ('MEDICAL', 'Medical Document'), ('ID_PROOF', 'ID Proof'), ('PHOTO', 'Photograph'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'student_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('date', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('vaccination_name', models.CharField(blank=True, max_length=100)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('examined_by', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'student_health_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('remark_type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('COMPLAINT', 'Complaint'), ('ACHIEVEMENT', 'Achievement'), ('DISCIPLINE', 'Discipline'), ('SYSTEM', 'System Generated')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('BEHAVIORAL', 'Behavioral'), ('ATTENDANCE', 'Attendance'), ('TRANSPORT', 'Transport'), ('LIBRARY', 'Library'), ('HOSTEL', 'Hostel'), ('HEALTH', 'Health'), ('FINANCE', 'Finance'), ('GENERAL', 'General')], db_index=True, max_length=20)),
                ('title', models.CharField(help_text='Brief title of the remark', max_length=200)),
                ('description', models.TextField(help_text='Detailed description')),
                ('visible_to_parent', models.BooleanField(default=True, help_text='Whether parents can see this remark')),
                ('visible_to_student', models.BooleanField(default=False, help_text='Whether student can see this remark')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important/urgent')),
                ('is_system_generated', models.BooleanField(default=False, help_text='Auto-generated by system')),
                ('source_module', models.CharField(blank=True, help_text='Module that generated this remark (e.g., library, transport)', max_length=50)),
                ('source_reference', models.CharField(blank=True, help_text='Reference ID from source module', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='student_remarks/')),
                ('requires_action', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_notes', models.TextField(blank=True)),
                ('parent_acknowledged', models.BooleanField(default=False)),
                ('parent_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_remarks_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Remark',
                'verbose_name_plural': 'Student Remarks',
                'db_table': 'student_remarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='student_rem_student_9cdeec_idx'), models.Index(fields=['remark_type', 'category'], name='student_rem_remark__f860d8_idx'), models.Index(fields=['visible_to_parent'], name='student_rem_visible_12cca9_idx')],
            },
        ),
    ]
