# Generated by Django 5.1.4 on 2025-12-28 00:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('roll_number', models.CharField(blank=True, help_text='Roll number for this session', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('DETAINED', 'Detained'), ('SUSPENDED', 'Suspended'), ('LEFT', 'Left'), ('TRANSFERRED', 'Transferred'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', help_text='Enrollment status', max_length=20)),
                ('enrollment_date', models.DateField(help_text='Date of enrollment in this session')),
                ('exit_date', models.DateField(blank=True, help_text='Date of exit from this session', null=True)),
                ('exit_reason', models.TextField(blank=True, help_text='Reason for exit (if applicable)')),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('final_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for this enrollment')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'db_table': 'student_enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_admissi_664d58_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_current_bec9d4_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(help_text='Date of admission to school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(db_index=True, help_text='Unique admission number', max_length=50),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'admission_number'], name='students_tenant__e05835_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('tenant', 'admission_number'), name='unique_admission_number_per_tenant'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for this enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='promoted_to_section',
            field=models.ForeignKey(blank=True, help_text='Section promoted to (if promoted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_enrollments', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(help_text='Section (which links to grade level)', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(help_text='Student profile', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['tenant', 'academic_year', 'status'], name='student_enr_tenant__b1960a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', '-enrollment_date'], name='student_enr_student_438906_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['section', 'status'], name='student_enr_section_dd8c70_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_per_academic_year'),
        ),
    ]
