# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnievent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alumnieventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.alumnievent'),
        ),
        migrations.AddField(
            model_name='alumnieventregistration',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant for RLS (denormalized from event)', on_delete=django.db.models.deletion.CASCADE, related_name='alumni_event_registrations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alumnijobposting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_jobs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant for RLS (denormalized from student)', on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='alumnijobposting',
            name='posted_by_alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to='students.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnieventregistration',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='students.alumniprofile'),
        ),
        migrations.AddField(
            model_name='alumnidonation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='students.alumniprofile'),
        ),
        migrations.AddField(
            model_name='bulkstudentimport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_imports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bulkstudentimport',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.communicationtemplate'),
        ),
        migrations.AddField(
            model_name='counselingrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this counseling record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_counseling_records', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='counselingrecord',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counselingrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this disciplinary action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_disciplinary_actions', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_actions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_actions_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='enhancedstudentdocument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.documentcategory'),
        ),
        migrations.AddField(
            model_name='enhancedstudentdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enhancedstudentdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_level',
            field=models.ForeignKey(blank=True, help_text='Template for specific grade (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this leave application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leave_applications', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentteachermeeting',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_parent_teacher_meetings', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='parentteachermeeting',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_meetings_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentteachermeeting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meetings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentteachermeeting',
            name='requested_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.parentuser'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='applied_by_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications_submitted', to='students.parentuser'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='students',
            field=models.ManyToManyField(help_text='Students linked to this parent', related_name='parent_accounts', to='students.student'),
        ),
        migrations.AddField(
            model_name='parentteachermeeting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meetings', to='students.student'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='enhancedstudentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_documents', to='students.student'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='students.student'),
        ),
        migrations.AddField(
            model_name='counselingrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_received', to='students.student'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentauditlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentauditlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_audit_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentbehaviorpoint',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this behavior record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_behavior_points', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentbehaviorpoint',
            name='awarded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_points_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentbehaviorpoint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_points', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentbehaviorpoint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_points', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant for RLS (denormalized from student)', on_delete=django.db.models.deletion.CASCADE, related_name='student_documents_all', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for this enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='promoted_to_section',
            field=models.ForeignKey(blank=True, help_text='Section promoted to (if promoted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_enrollments', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='section',
            field=models.ForeignKey(help_text='Section (which links to grade level)', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(help_text='Student profile', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studenthealthrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this health record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_health_records', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studenthealthrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='studenthealthrecord',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant for RLS (denormalized from student)', on_delete=django.db.models.deletion.CASCADE, related_name='student_health_records_all', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.idcardtemplate'),
        ),
        migrations.AddField(
            model_name='studentidcard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='academic_year_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='academic_year_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='promoted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='section_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='section_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentpromotiondetail',
            name='enrollment_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studentpromotiondetail',
            name='enrollment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='students.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studentpromotiondetail',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='students.studentpromotion'),
        ),
        migrations.AddField(
            model_name='studentpromotiondetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentpromotiondetail',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant for RLS (denormalized from student)', on_delete=django.db.models.deletion.CASCADE, related_name='student_promotion_details', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this remark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_remarks', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='created_by_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_remarks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant for RLS (denormalized from student)', on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transfers', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='from_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transfers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='to_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='tenants.section'),
        ),
        migrations.AddConstraint(
            model_name='alumnieventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'alumni'), name='unique_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_document_category_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'admission_number'], name='students_tenant__e05835_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['family_id'], name='students_family__44d5e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('tenant', 'admission_number'), name='unique_admission_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='enhancedstudentdocument',
            index=models.Index(fields=['student', 'verification_status'], name='enhanced_st_student_4fba41_idx'),
        ),
        migrations.AddIndex(
            model_name='enhancedstudentdocument',
            index=models.Index(fields=['expiry_date'], name='enhanced_st_expiry__8d08dd_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['student', '-created_at'], name='communicati_student_f8fb98_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['status', '-created_at'], name='communicati_status_510449_idx'),
        ),
        migrations.AddIndex(
            model_name='studentauditlog',
            index=models.Index(fields=['student', '-created_at'], name='student_aud_student_5327f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentauditlog',
            index=models.Index(fields=['action', '-created_at'], name='student_aud_action_783bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbehaviorpoint',
            index=models.Index(fields=['student', '-created_at'], name='student_beh_student_15045e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['student', 'document_type'], name='student_doc_student_db5152_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['verification_status', 'created_at'], name='student_doc_verific_875cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['expiry_date'], name='student_doc_expiry__e8f84b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['tenant', 'academic_year', 'status'], name='student_enr_tenant__b1960a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', '-enrollment_date'], name='student_enr_student_438906_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['section', 'status'], name='student_enr_section_dd8c70_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_per_academic_year'),
        ),
        migrations.AddIndex(
            model_name='studentremark',
            index=models.Index(fields=['student', '-created_at'], name='student_rem_student_9cdeec_idx'),
        ),
        migrations.AddIndex(
            model_name='studentremark',
            index=models.Index(fields=['remark_type', 'category'], name='student_rem_remark__f860d8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentremark',
            index=models.Index(fields=['visible_to_parent'], name='student_rem_visible_12cca9_idx'),
        ),
    ]
