# Generated by Django 5.2.9 on 2026-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='Aadhar Card Number (12 digits)', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='aapar_number',
            field=models.CharField(blank=True, help_text='Aapar Number / Other ID', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pen_number',
            field=models.CharField(blank=True, help_text='Permanent Education Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(max_length=20),
        ),
    ]
