# Generated by Django 5.2.9 on 2026-09-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_initial'),
        ('tenants', '0008_tenantsettings_auto_mark_absent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='manual_qr_code',
            field=models.CharField(blank=True, db_index=True, help_text='Manually assigned/external QR code text. Resolves to this student in addition to the system-generated QR.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='manual_qr_code',
            field=models.CharField(blank=True, db_index=True, help_text='Manually assigned/external QR code text. Resolves to this student in addition to the system-generated QR.', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['manual_qr_code'], name='students_manual__ecd211_idx'),
        ),
    ]
