# Generated by Django 5.2.9 on 2026-01-07 11:51

import core.fields
import core.utils
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_historical_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='aadhar_number',
            field=core.fields.EncryptedCharField(blank=True, help_text='Aadhar Card Number (12 digits) - Encrypted', max_length=255, validators=[core.utils.validate_aadhar]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(), core.utils.validate_email_enhanced]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(), core.utils.validate_email_enhanced]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='father_phone',
            field=models.CharField(max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for this record'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(), core.utils.validate_email_enhanced]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_phone',
            field=models.CharField(max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterModelTable(
            name='historicalstudent',
            table=None,
        ),
    ]
