# Generated by Django 5.2.9 on 2026-01-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_historicalstudent_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='citizenship',
            field=models.CharField(blank=True, default='', help_text='Citizenship Status', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='father_profession',
            field=models.CharField(blank=True, help_text='Father Profession/Job Title', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle Name (Optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='mother_profession',
            field=models.CharField(blank=True, help_text='Mother Profession/Job Title', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='previous_school_address',
            field=models.TextField(blank=True, help_text='Address of Previous School'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='previous_school_class',
            field=models.CharField(blank=True, help_text='Last Class/Grade Attended', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='previous_school_name',
            field=models.CharField(blank=True, help_text='Name of Previous School', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='transfer_certificate_number',
            field=models.CharField(blank=True, help_text='Transfer Certificate Number', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.CharField(blank=True, default='', help_text='Citizenship Status', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='father_profession',
            field=models.CharField(blank=True, help_text='Father Profession/Job Title', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle Name (Optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_profession',
            field=models.CharField(blank=True, help_text='Mother Profession/Job Title', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_address',
            field=models.TextField(blank=True, help_text='Address of Previous School'),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_class',
            field=models.CharField(blank=True, help_text='Last Class/Grade Attended', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, help_text='Name of Previous School', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_certificate_number',
            field=models.CharField(blank=True, help_text='Transfer Certificate Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name (Optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name (Optional)', max_length=100),
        ),
    ]
