# Generated by Django 5.2.9 on 2026-01-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_historicalstudent_citizenship_and_more'),
        ('students', '0011_historicalstudent_citizenship_and_more'),
    ]

    operations = [
    ]
