# Generated by Django 5.2.9 on 2026-01-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_icon_theme'),
        ('students', '0012_merge_20260115_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentremark',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this remark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_remarks', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studenthealthrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this health record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_health_records', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studenttransfer',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_transfers', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this leave application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leave_applications', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='studentbehaviorpoint',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this behavior record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_behavior_points', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this disciplinary action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_disciplinary_actions', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='counselingrecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this counseling record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_counseling_records', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='parentteachermeeting',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_parent_teacher_meetings', to='tenants.academicyear'),
        ),
    ]