# Generated by Django 5.2.9 on 2026-01-15 10:00

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_add_academic_year_to_student_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.utils.validate_indian_phone]),
        ),
    ]
