# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GOOD', 'Good Habit'), ('BAD', 'Bad Habit')], max_length=50)),
                ('points', models.IntegerField(default=1, help_text='Points added/deducted')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='StudentHabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_awarded', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'student_habit_logs',
                'ordering': ['-date'],
            },
        ),
    ]
