# Generated by Django 5.1.4 on 2025-12-30 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GOOD', 'Good Habit'), ('BAD', 'Bad Habit')], max_length=50)),
                ('points', models.IntegerField(default=1, help_text='Points added/deducted')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='StudentHabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_awarded', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_tracker.habit')),
                ('staff', models.ForeignKey(help_text='Teacher who awarded points', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='students.student')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'student_habit_logs',
                'ordering': ['-date'],
            },
        ),
    ]
