# Generated by Django 5.1.4 on 2025-12-27 20:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Plan name (e.g., Basic, Pro, Enterprise)', max_length=100)),
                ('plan_type', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], db_index=True, help_text='Plan type identifier', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Plan description and features')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price in base currency', max_digits=10)),
                ('price_quarterly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quarterly price (usually discounted)', max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Yearly price (usually discounted)', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Currency code (INR, USD, etc.)', max_length=3)),
                ('max_students', models.PositiveIntegerField(default=100, help_text='Maximum number of students allowed')),
                ('max_staff', models.PositiveIntegerField(default=20, help_text='Maximum number of staff members allowed')),
                ('max_storage_gb', models.PositiveIntegerField(default=5, help_text='Maximum storage in GB')),
                ('features', models.JSONField(default=dict, help_text='Plan features as JSON (e.g., {"sms": true, "whatsapp": false})')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Number of trial days for this plan')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this plan is currently available for purchase')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this plan is publicly visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order on pricing page')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='trial', help_text='Current subscription status', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle for this subscription', max_length=20)),
                ('trial_start_date', models.DateTimeField(blank=True, help_text='When trial started', null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='When trial ends', null=True)),
                ('current_period_start', models.DateTimeField(help_text='Start of current billing period')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When subscription was canceled', null=True)),
                ('auto_renew', models.BooleanField(default=True, help_text='Whether subscription auto-renews')),
                ('razorpay_subscription_id', models.CharField(blank=True, help_text='Razorpay subscription ID', max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional subscription metadata')),
                ('tenant', models.OneToOneField(help_text='Tenant this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
                ('plan', models.ForeignKey(help_text='Current subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number', max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount (GST, VAT, etc.)', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be paid', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Invoice status', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Invoice issue date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When invoice was paid', null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='URL to invoice PDF', max_length=500)),
                ('razorpay_invoice_id', models.CharField(blank=True, help_text='Razorpay invoice ID', max_length=100)),
                ('stripe_invoice_id', models.CharField(blank=True, help_text='Stripe invoice ID', max_length=100)),
                ('line_items', models.JSONField(default=list, help_text='Invoice line items')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional invoice metadata')),
                ('subscription', models.ForeignKey(help_text='Subscription this invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], help_text='Payment gateway used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Transaction status', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, help_text='Payment gateway transaction ID', max_length=200)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment gateway payment ID', max_length=200)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method (card, UPI, netbanking, etc.)', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full gateway response')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('invoice', models.ForeignKey(help_text='Invoice this transaction is for', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='payment_tra_invoice_f76be2_idx'), models.Index(fields=['gateway', 'gateway_transaction_id'], name='payment_tra_gateway_790140_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription', 'status'], name='invoices_subscri_cd89af_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoices_issue_d_6fe766_idx'),
        ),
    ]
