# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(help_text='Tenant this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(help_text='Subscription this invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text='Current subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['invoice', 'status'], name='payment_tra_invoice_f76be2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'gateway_transaction_id'], name='payment_tra_gateway_790140_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription', 'status'], name='invoices_subscri_cd89af_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoices_issue_d_6fe766_idx'),
        ),
    ]
