# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalahRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('salah_name', models.CharField(choices=[('FAJR', 'Fajr'), ('DHUHR', 'Dhuhr'), ('ASR', 'Asr'), ('MAGHRIB', 'Maghrib'), ('ISHA', 'Isha')], max_length=10)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered (Jamaat)'), ('INDIVIDUAL', 'Offered (Individual)'), ('MISSED', 'Missed'), ('EXCUSED', 'Excused')], default='MISSED', max_length=20)),
            ],
            options={
                'db_table': 'salah_records',
                'ordering': ['-date', 'salah_name'],
            },
        ),
    ]
