# Generated by Django 5.1.4 on 2025-12-30 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalahRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('salah_name', models.CharField(choices=[('FAJR', 'Fajr'), ('DHUHR', 'Dhuhr'), ('ASR', 'Asr'), ('MAGHRIB', 'Maghrib'), ('ISHA', 'Isha')], max_length=10)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered (Jamaat)'), ('INDIVIDUAL', 'Offered (Individual)'), ('MISSED', 'Missed'), ('EXCUSED', 'Excused')], default='MISSED', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salah_records', to='students.student')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff')),
            ],
            options={
                'db_table': 'salah_records',
                'ordering': ['-date', 'salah_name'],
                'unique_together': {('student', 'date', 'salah_name')},
            },
        ),
    ]
