import os
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from django.db import connection

sqls = [
    """CREATE TABLE IF NOT EXISTS parent_users (id uuid NOT NULL PRIMARY KEY, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, is_deleted boolean NOT NULL, deleted_at timestamp with time zone NULL, relation_type varchar(20) NOT NULL, occupation varchar(200) NOT NULL, office_address text NOT NULL, preferred_language varchar(10) NOT NULL, email_notifications boolean NOT NULL, sms_notifications boolean NOT NULL, push_notifications boolean NOT NULL, portal_access_enabled boolean NOT NULL, last_login_at timestamp with time zone NULL, user_id integer NULL, tenant_id uuid NULL)""",
    """CREATE TABLE IF NOT EXISTS parent_users_students (id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, parentuser_id uuid NOT NULL, student_id uuid NOT NULL)""",
]

with connection.cursor() as cursor:
    for sql in sqls:
        try:
            cursor.execute(sql)
            print("Executed successfully")
        except Exception as e:
            print(f"Error: {e}")

print("Done!")
