# Generated by Django 5.1.4 on 2026-01-19 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date')),
                ('total_days', models.DecimalField(decimal_places=1, help_text='Total leave days', max_digits=5)),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Application status', max_length=20)),
                ('applied_on', models.DateTimeField(blank=True, help_text='When the leave was applied', null=True)),
                ('approved_on', models.DateTimeField(blank=True, help_text='When the leave was approved/rejected', null=True)),
                ('approval_remarks', models.TextField(blank=True, help_text='Remarks from approver')),
                ('attachment', models.FileField(blank=True, help_text='Supporting document (e.g., medical certificate)', null=True, upload_to='leave_applications/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'db_table': 'leave_applications',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('total_quota', models.DecimalField(decimal_places=1, help_text='Total leave quota for the year', max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0.0, help_text='Leave days used', max_digits=5)),
                ('pending', models.DecimalField(decimal_places=1, default=0.0, help_text='Leave days pending approval', max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0.0, help_text='Leave days carried forward from previous year', max_digits=5)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(help_text='Leave type name (e.g., Sick Leave)', max_length=100)),
                ('code', models.CharField(help_text='Short code (e.g., SL, CL, EL)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Leave type description')),
                ('default_quota', models.DecimalField(decimal_places=1, default=0.0, help_text='Default annual quota (days)', max_digits=5)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave type is paid')),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether this leave requires approval')),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed', null=True)),
                ('carry_forward', models.BooleanField(default=False, help_text='Can unused leave be carried forward')),
                ('max_carry_forward', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum days that can be carried forward', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this leave type is active')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'leave_types',
                'ordering': ['name'],
            },
        ),
    ]
