# Generated by Django 5.1.4 on 2025-12-30 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Leave type name (e.g., Sick Leave)', max_length=100)),
                ('code', models.CharField(help_text='Short code (e.g., SL, CL, EL)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Leave type description')),
                ('default_quota', models.DecimalField(decimal_places=1, default=0.0, help_text='Default annual quota (days)', max_digits=5)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this leave type is paid')),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether this leave requires approval')),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed', null=True)),
                ('carry_forward', models.BooleanField(default=False, help_text='Can unused leave be carried forward')),
                ('max_carry_forward', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum days that can be carried forward', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this leave type is active')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'leave_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('total_quota', models.DecimalField(decimal_places=1, help_text='Total leave quota for the year', max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0.0, help_text='Leave days used', max_digits=5)),
                ('pending', models.DecimalField(decimal_places=1, default=0.0, help_text='Leave days pending approval', max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0.0, help_text='Leave days carried forward from previous year', max_digits=5)),
                ('academic_year', models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='tenants.academicyear')),
                ('staff', models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(help_text='Leave type', on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('start_date', models.DateField(help_text='Leave start date')),
                ('end_date', models.DateField(help_text='Leave end date')),
                ('total_days', models.DecimalField(decimal_places=1, help_text='Total leave days', max_digits=5)),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Application status', max_length=20)),
                ('applied_on', models.DateTimeField(blank=True, help_text='When the leave was applied', null=True)),
                ('approved_on', models.DateTimeField(blank=True, help_text='When the leave was approved/rejected', null=True)),
                ('approval_remarks', models.TextField(blank=True, help_text='Remarks from approver')),
                ('attachment', models.FileField(blank=True, help_text='Supporting document (e.g., medical certificate)', null=True, upload_to='leave_applications/%Y/%m/')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Who approved/rejected the leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='staff.staff')),
                ('staff', models.ForeignKey(help_text='Staff member applying for leave', on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_applications', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(help_text='Type of leave', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'db_table': 'leave_applications',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['tenant', 'is_active'], name='leave_types_tenant__9ef8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['tenant', 'staff', 'academic_year'], name='leave_balan_tenant__8d4722_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('staff', 'leave_type', 'academic_year'), name='unique_leave_balance'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['tenant', 'staff', 'status'], name='leave_appli_tenant__097d90_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['status', 'applied_on'], name='leave_appli_status_a64f39_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_appli_start_d_424510_idx'),
        ),
    ]
