# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Who approved/rejected the leave', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='staff',
            field=models.ForeignKey(help_text='Staff member applying for leave', on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_applications', to='staff.staff'),
        ),
    ]
