# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='staff',
            field=models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(help_text='Leave type', on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(help_text='Type of leave', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.leavetype'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['tenant', 'is_active'], name='leave_types_tenant__9ef8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['tenant', 'staff', 'academic_year'], name='leave_balan_tenant__8d4722_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('staff', 'leave_type', 'academic_year'), name='unique_leave_balance'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['tenant', 'staff', 'status'], name='leave_appli_tenant__097d90_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['status', 'applied_on'], name='leave_appli_status_a64f39_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_appli_start_d_424510_idx'),
        ),
    ]
