# Generated by Django 5.1.4 on 2025-12-28 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('card_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('VISITOR', 'Visitor')], max_length=20)),
                ('orientation', models.CharField(choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical')], default='VERTICAL', max_length=20)),
                ('width_mm', models.DecimalField(decimal_places=2, default=85.6, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, default=53.98, max_digits=6)),
                ('design_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_designs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Design',
                'verbose_name_plural': 'ID Card Designs',
                'db_table': 'id_card_designs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDCardGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('card_type', models.CharField(max_length=20)),
                ('filters', models.JSONField(default=dict, help_text="Filters applied (e.g., {'grade': 'Class 5'})")),
                ('total_cards', models.IntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='idcard_outputs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='idcards.idcarddesign')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_generations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Generation',
                'verbose_name_plural': 'ID Card Generations',
                'db_table': 'id_card_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('card_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('VISITOR', 'Visitor')], help_text='Type of ID card', max_length=20)),
                ('orientation', models.CharField(choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical')], default='VERTICAL', max_length=20)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('CORPORATE', 'Corporate'), ('PLAYFUL', 'Playful'), ('MINIMALIST', 'Minimalist'), ('MODERN', 'Modern'), ('CLASSIC', 'Classic')], default='ACADEMIC', max_length=20)),
                ('width_mm', models.DecimalField(decimal_places=2, default=85.6, help_text='Card width in mm', max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, default=53.98, help_text='Card height in mm', max_digits=6)),
                ('design_json', models.JSONField(default=dict, help_text='JSON design configuration')),
                ('preview_image', models.ImageField(blank=True, help_text='Preview image', null=True, upload_to='idcard_templates/')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all tenants')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (null for global templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
                'db_table': 'id_card_templates',
                'ordering': ['category', 'name'],
            },
        ),
    ]
