# Generated by Django 5.1.4 on 2025-12-30 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=45)),
                ('provider', models.CharField(choices=[('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('JITSI', 'Jitsi Meet')], default='ZOOM', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('passcode', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('recording_link', models.URLField(blank=True, max_length=500)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='tenants.gradelevel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='tenants.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_classes', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lms_live_classes',
                'ordering': ['-start_time'],
            },
        ),
    ]
