# Generated by Django 5.1.4 on 2026-01-19 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=45)),
                ('provider', models.CharField(choices=[('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('JITSI', 'Jitsi Meet')], default='ZOOM', max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('meeting_id', models.CharField(blank=True, max_length=100)),
                ('passcode', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('recording_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'lms_live_classes',
                'ordering': ['-start_time'],
            },
        ),
    ]
