# Generated by Django 5.1.4 on 2025-12-30 12:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Detailed assignment description and instructions')),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('LAB', 'Lab Work'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other')], default='HOMEWORK', help_text='Type of assignment', max_length=20)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when assignment was assigned')),
                ('due_date', models.DateTimeField(help_text='Submission deadline')),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum marks for this assignment', max_digits=6)),
                ('attachment', models.FileField(blank=True, help_text='Assignment file (PDF, DOC, etc.)', null=True, upload_to='assignments/attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Assignment status', max_length=20)),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Allow submissions after due date')),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty percentage for late submissions', max_digits=5)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for students')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.academicyear')),
                ('section', models.ForeignKey(help_text='Section/Class this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.section')),
                ('subject', models.ForeignKey(help_text='Subject this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('submission_file', models.FileField(blank=True, help_text='Submitted file (PDF, DOC, images, etc.)', null=True, upload_to='assignments/submissions/%Y/%m/')),
                ('submission_text', models.TextField(blank=True, help_text='Text submission (if applicable)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when submitted', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned')], default='DRAFT', help_text='Submission status', max_length=20)),
                ('is_late', models.BooleanField(default=False, help_text='Whether submission was late')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded', max_digits=6, null=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='Timestamp when graded', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Teacher feedback and remarks')),
                ('feedback_file', models.FileField(blank=True, help_text='Feedback file with annotations', null=True, upload_to='assignments/feedback/%Y/%m/')),
                ('student_notes', models.TextField(blank=True, help_text='Student notes or comments')),
                ('assignment', models.ForeignKey(help_text='Assignment this submission is for', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Teacher who graded this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='staff.staff')),
                ('student', models.ForeignKey(help_text='Student who submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'academic_year', 'section'], name='assignments_tenant__194b31_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'subject'], name='assignments_tenant__78f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='assignments_tenant__44ef71_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher', 'status'], name='assignments_teacher_81f6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', 'assignment', 'status'], name='submissions_tenant__469203_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', 'student', 'status'], name='submissions_tenant__718bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_ac0821_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_student'),
        ),
    ]
