# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(help_text='Detailed assignment description and instructions')),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('LAB', 'Lab Work'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other')], default='HOMEWORK', help_text='Type of assignment', max_length=20)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when assignment was assigned')),
                ('due_date', models.DateTimeField(help_text='Submission deadline')),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum marks for this assignment', max_digits=6)),
                ('attachment', models.FileField(blank=True, help_text='Assignment file (PDF, DOC, etc.)', null=True, upload_to='assignments/attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Assignment status', max_length=20)),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Allow submissions after due date')),
                ('late_penalty_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty percentage for late submissions', max_digits=5)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for students')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(help_text='Chapter name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Chapter description')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('estimated_hours', models.IntegerField(default=1, help_text='Estimated teaching hours')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topics in this chapter')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether chapter is completed')),
                ('completed_date', models.DateField(blank=True, help_text='Date when completed', null=True)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'syllabus_chapters',
                'ordering': ['syllabus', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('title', models.CharField(help_text='Homework title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Homework description')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, help_text='Date when assigned')),
                ('due_date', models.DateField(help_text='Due date')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Priority level', max_length=10)),
                ('attachment', models.FileField(blank=True, help_text='Attachment file', null=True, upload_to='homework/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'db_table': 'homework',
                'ordering': ['-assigned_date', '-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Completion timestamp', null=True)),
                ('notes', models.TextField(blank=True, help_text='Student notes')),
            ],
            options={
                'verbose_name': 'Homework Completion',
                'verbose_name_plural': 'Homework Completions',
                'db_table': 'homework_completions',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('submission_file', models.FileField(blank=True, help_text='Submitted file (PDF, DOC, images, etc.)', null=True, upload_to='assignments/submissions/%Y/%m/')),
                ('submission_text', models.TextField(blank=True, help_text='Text submission (if applicable)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when submitted', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED', 'Returned')], default='DRAFT', help_text='Submission status', max_length=20)),
                ('is_late', models.BooleanField(default=False, help_text='Whether submission was late')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded', max_digits=6, null=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='Timestamp when graded', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Teacher feedback and remarks')),
                ('feedback_file', models.FileField(blank=True, help_text='Feedback file with annotations', null=True, upload_to='assignments/feedback/%Y/%m/')),
                ('student_notes', models.TextField(blank=True, help_text='Student notes or comments')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(help_text='Syllabus name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Syllabus description')),
                ('total_hours', models.IntegerField(default=0, help_text='Total teaching hours')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabi',
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='SyllabusProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether completed for this section')),
                ('completed_date', models.DateField(blank=True, help_text='Date when completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Teaching notes')),
            ],
            options={
                'verbose_name': 'Syllabus Progress',
                'verbose_name_plural': 'Syllabus Progress Records',
                'db_table': 'syllabus_progress',
            },
        ),
    ]
