# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for this assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(help_text='Section/Class this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(help_text='Subject this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who marked this complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_chapters', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='homework',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='homework',
            name='section',
            field=models.ForeignKey(help_text='Section/Class', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who assigned this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homework', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='homework',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='homeworkcompletion',
            name='homework',
            field=models.ForeignKey(help_text='The homework', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='academics.homework'),
        ),
        migrations.AddField(
            model_name='homeworkcompletion',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='homework_completions', to='students.student'),
        ),
        migrations.AddField(
            model_name='homeworkcompletion',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(help_text='Assignment this submission is for', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who graded this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(help_text='Student who submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='submission',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='grade_level',
            field=models.ForeignKey(help_text='Grade level', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='syllabus',
            field=models.ForeignKey(help_text='Parent syllabus', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='chapter',
            field=models.ForeignKey(help_text='Chapter', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academics.chapter'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='section',
            field=models.ForeignKey(help_text='Section', on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_progress', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='syllabus',
            field=models.ForeignKey(help_text='Syllabus', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academics.syllabus'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher who updated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_progress_updates', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='syllabusprogress',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'academic_year', 'section'], name='assignments_tenant__194b31_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'subject'], name='assignments_tenant__78f70b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='assignments_tenant__44ef71_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['teacher', 'status'], name='assignments_teacher_81f6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['tenant', 'section', 'due_date'], name='homework_tenant__66cdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['tenant', 'subject', 'assigned_date'], name='homework_tenant__81d06b_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkcompletion',
            index=models.Index(fields=['tenant', 'student', 'is_completed'], name='homework_co_tenant__281146_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworkcompletion',
            constraint=models.UniqueConstraint(fields=('homework', 'student'), name='unique_homework_completion_per_student'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', 'assignment', 'status'], name='submissions_tenant__469203_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', 'student', 'status'], name='submissions_tenant__718bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_ac0821_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_student'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['tenant', 'subject', 'grade_level'], name='syllabus_tenant__d903b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('tenant', 'subject', 'grade_level', 'academic_year'), name='unique_syllabus_per_subject_grade_year'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['tenant', 'syllabus', 'is_completed'], name='syllabus_ch_tenant__2b0785_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabusprogress',
            index=models.Index(fields=['tenant', 'section', 'is_completed'], name='syllabus_pr_tenant__3364a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='syllabusprogress',
            constraint=models.UniqueConstraint(fields=('syllabus', 'section', 'chapter'), name='unique_progress_per_section_chapter'),
        ),
    ]
