# Generated by Django 5.1.4 on 2026-01-16 06:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_assignment_deleted_by_submission_deleted_by'),
        ('staff', '0003_appraisalcycle_deleted_by_staff_deleted_by_and_more'),
        ('students', '0014_alter_historicalstudent_address_and_more'),
        ('tenants', '0010_add_icon_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Homework title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Homework description')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, help_text='Date when assigned')),
                ('due_date', models.DateField(help_text='Due date')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text='Priority level', max_length=10)),
                ('attachment', models.FileField(blank=True, help_text='Attachment file', null=True, upload_to='homework/%Y/%m/')),
                ('academic_year', models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.academicyear')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(help_text='Section/Class', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.section')),
                ('subject', models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='tenants.subject')),
                ('teacher', models.ForeignKey(help_text='Teacher who assigned this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homework', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'db_table': 'homework',
                'ordering': ['-assigned_date', '-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Completion timestamp', null=True)),
                ('notes', models.TextField(blank=True, help_text='Student notes')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(help_text='The homework', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='academics.homework')),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='homework_completions', to='students.student')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Homework Completion',
                'verbose_name_plural': 'Homework Completions',
                'db_table': 'homework_completions',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Syllabus name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Syllabus description')),
                ('total_hours', models.IntegerField(default=0, help_text='Total teaching hours')),
                ('academic_year', models.ForeignKey(help_text='Academic year', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='tenants.academicyear')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(help_text='Grade level', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='tenants.gradelevel')),
                ('subject', models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabi',
                'db_table': 'syllabus',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Chapter name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Chapter description')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('estimated_hours', models.IntegerField(default=1, help_text='Estimated teaching hours')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topics in this chapter')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether chapter is completed')),
                ('completed_date', models.DateField(blank=True, help_text='Date when completed', null=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='Teacher who marked this complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_chapters', to='staff.staff')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('syllabus', models.ForeignKey(help_text='Parent syllabus', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.syllabus')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'syllabus_chapters',
                'ordering': ['syllabus', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether completed for this section')),
                ('completed_date', models.DateField(blank=True, help_text='Date when completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Teaching notes')),
                ('chapter', models.ForeignKey(help_text='Chapter', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academics.chapter')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(help_text='Section', on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_progress', to='tenants.section')),
                ('syllabus', models.ForeignKey(help_text='Syllabus', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academics.syllabus')),
                ('teacher', models.ForeignKey(help_text='Teacher who updated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_progress_updates', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Syllabus Progress',
                'verbose_name_plural': 'Syllabus Progress Records',
                'db_table': 'syllabus_progress',
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['tenant', 'section', 'due_date'], name='homework_tenant__66cdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['tenant', 'subject', 'assigned_date'], name='homework_tenant__81d06b_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkcompletion',
            index=models.Index(fields=['tenant', 'student', 'is_completed'], name='homework_co_tenant__281146_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworkcompletion',
            constraint=models.UniqueConstraint(fields=('homework', 'student'), name='unique_homework_completion_per_student'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['tenant', 'subject', 'grade_level'], name='syllabus_tenant__d903b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('tenant', 'subject', 'grade_level', 'academic_year'), name='unique_syllabus_per_subject_grade_year'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['tenant', 'syllabus', 'is_completed'], name='syllabus_ch_tenant__2b0785_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabusprogress',
            index=models.Index(fields=['tenant', 'section', 'is_completed'], name='syllabus_pr_tenant__3364a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='syllabusprogress',
            constraint=models.UniqueConstraint(fields=('syllabus', 'section', 'chapter'), name='unique_progress_per_section_chapter'),
        ),
    ]
