# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('prediction_date', models.DateField(db_index=True)),
                ('churn_probability', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, max_length=10)),
                ('factors', models.JSONField(default=dict, help_text='Factors contributing to churn risk')),
                ('recommendations', models.JSONField(default=list, help_text='Recommended actions to prevent churn')),
            ],
            options={
                'verbose_name': 'Churn Prediction',
                'verbose_name_plural': 'Churn Predictions',
                'db_table': 'churn_predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantHealthAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('alert_type', models.CharField(choices=[('CHURN_RISK', 'Churn Risk'), ('LOW_HEALTH', 'Low Health Score'), ('HIGH_ERRORS', 'High Error Rate'), ('LOW_ENGAGEMENT', 'Low User Engagement'), ('LIMIT_REACHED', 'Limit Reached')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Health Alert',
                'verbose_name_plural': 'Health Alerts',
                'db_table': 'tenant_health_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('date', models.DateField(db_index=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('dau', models.IntegerField(default=0)),
                ('modules_used', models.JSONField(default=list, help_text='List of modules used today')),
                ('module_count', models.IntegerField(default=0)),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('database_rows', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Error rate percentage', max_digits=5)),
                ('avg_response_time_ms', models.IntegerField(default=0)),
                ('health_score', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Tenant Metric',
                'verbose_name_plural': 'Tenant Metrics',
                'db_table': 'tenant_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UpsellOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('opportunity_type', models.CharField(choices=[('LIMIT_APPROACHING', 'Approaching Limit'), ('FEATURE_REQUEST', 'Feature Request'), ('HIGH_USAGE', 'High Usage'), ('MODULE_INTEREST', 'Module Interest')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_plan', models.CharField(blank=True, max_length=50)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_usage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('usage_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Upsell Opportunity',
                'verbose_name_plural': 'Upsell Opportunities',
                'db_table': 'upsell_opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('API_CALL', 'API Call'), ('MODULE_ACCESS', 'Module Access'), ('FEATURE_USE', 'Feature Use'), ('ERROR', 'Error')], db_index=True, max_length=20)),
                ('module', models.CharField(blank=True, db_index=True, max_length=50)),
                ('feature', models.CharField(blank=True, max_length=100)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'db_table': 'usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
