# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnprediction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenanthealthalert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmetric',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='upsellopportunity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_opportunities', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='tenants.tenant'),
        ),
    ]
