# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='churnprediction',
            unique_together={('tenant', 'prediction_date')},
        ),
        migrations.AddIndex(
            model_name='tenanthealthalert',
            index=models.Index(fields=['tenant', '-created_at'], name='tenant_heal_tenant__f7fde5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanthealthalert',
            index=models.Index(fields=['alert_type', 'severity'], name='tenant_heal_alert_t_45267f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenanthealthalert',
            index=models.Index(fields=['is_resolved'], name='tenant_heal_is_reso_cd9aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmetric',
            index=models.Index(fields=['tenant', '-date'], name='tenant_metr_tenant__cc4284_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmetric',
            index=models.Index(fields=['date'], name='tenant_metr_date_35eaee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmetric',
            index=models.Index(fields=['health_score'], name='tenant_metr_health__7e3a54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmetric',
            unique_together={('tenant', 'date')},
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['tenant', '-created_at'], name='usage_logs_tenant__f0a8af_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['action_type', '-created_at'], name='usage_logs_action__127cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['is_error'], name='usage_logs_is_erro_a077e7_idx'),
        ),
    ]
