# Generated by Django 5.1.4 on 2026-09-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alert_rules_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='analytics_a_tenant__ac4e7d_idx',
            old_name='analytics_a_tenant__9a2db0_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='analytics_a_tenant__68b2e0_idx',
            old_name='analytics_a_tenant__b9d4be_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='analytics_a_tenant__d4511c_idx',
            old_name='analytics_a_tenant__f9e9b0_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='analytics_a_tenant__dd997a_idx',
            old_name='analytics_a_tenant__b8b24f_idx',
        ),
    ]
