# Generated by Django 5.1.4 on 2026-01-03 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('tenants', '0004_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='page',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='website',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='website',
            name='theme',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'slug')},
        ),
        migrations.RemoveField(
            model_name='section',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='section',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='section',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='section',
            name='padding',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='website',
            name='address',
        ),
        migrations.RemoveField(
            model_name='website',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='website',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='website',
            name='custom_domain',
        ),
        migrations.RemoveField(
            model_name='website',
            name='custom_domain_verified',
        ),
        migrations.RemoveField(
            model_name='website',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='google_analytics_id',
        ),
        migrations.RemoveField(
            model_name='website',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='map_latitude',
        ),
        migrations.RemoveField(
            model_name='website',
            name='map_longitude',
        ),
        migrations.RemoveField(
            model_name='website',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='website',
            name='site_tagline',
        ),
        migrations.RemoveField(
            model_name='website',
            name='site_title',
        ),
        migrations.RemoveField(
            model_name='website',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='website',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('FEATURES', 'Features'), ('ABOUT', 'About'), ('GALLERY', 'Gallery'), ('TESTIMONIALS', 'Testimonials'), ('CONTACT', 'Contact Form'), ('CTA', 'Call to Action'), ('TEXT', 'Text Block'), ('HTML', 'Custom HTML')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='cms/favicons/'),
        ),
        migrations.AddField(
            model_name='website',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cms/logos/'),
        ),
        migrations.AddField(
            model_name='website',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='Default Website', max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='primary_color',
            field=models.CharField(default='#1976D2', max_length=7),
        ),
        migrations.AddField(
            model_name='website',
            name='secondary_color',
            field=models.CharField(default='#424242', max_length=7),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='page',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True),
        ),

        migrations.AlterField(
            model_name='page',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='cms.website'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True),
        ),

        migrations.AlterField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='website',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True),
        ),

        migrations.AlterField(
            model_name='website',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='website',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='cms/media/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'cms_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('label', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.website')),
            ],
            options={
                'db_table': 'cms_menu_items',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_type',
        ),
    ]
