# Generated by Django 5.2.9 on 2026-01-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_media_deleted_by_menuitem_deleted_by_page_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('ABOUT', 'About'), ('ACADEMICS', 'Academics'), ('ADMISSIONS', 'Admissions'), ('CONTACT', 'Contact'), ('GALLERY', 'Gallery'), ('EVENTS', 'Events'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('FEATURES', 'Features'), ('ABOUT', 'About'), ('GALLERY', 'Gallery'), ('TESTIMONIALS', 'Testimonials'), ('CONTACT', 'Contact Form'), ('CTA', 'Call to Action'), ('TEXT', 'Text Block'), ('HTML', 'Custom HTML'), ('STATS', 'Statistics'), ('PRINCIPAL_MESSAGE', 'Principal Message'), ('PAGE_HEADER', 'Page Header'), ('TEXT_WITH_IMAGE', 'Text with Image'), ('MISSION_VISION', 'Mission & Vision'), ('IMAGE_GRID', 'Image Grid'), ('TIMELINE', 'Timeline'), ('PROGRAMS', 'Programs'), ('MAP', 'Map'), ('FAQ', 'FAQ')], default='TEXT', max_length=30),
        ),
    ]
