# Generated by Django 5.2.9 on 2026-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_page_type_section_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('HERO', 'Hero Section'), ('FEATURES', 'Features'), ('ABOUT', 'About'), ('GALLERY', 'Gallery'), ('TESTIMONIALS', 'Testimonials'), ('CONTACT', 'Contact Form'), ('CTA', 'Call to Action'), ('TEXT', 'Text Block'), ('TEXT_BLOCK', 'Rich Text Block'), ('HTML', 'Custom HTML'), ('STATS', 'Statistics'), ('PRINCIPAL_MESSAGE', 'Principal Message'), ('PAGE_HEADER', 'Page Header'), ('TEXT_WITH_IMAGE', 'Text with Image'), ('MISSION_VISION', 'Mission & Vision'), ('IMAGE_GRID', 'Image Grid'), ('TIMELINE', 'Timeline'), ('PROGRAMS', 'Programs'), ('MAP', 'Map'), ('FAQ', 'FAQ'), ('NEWS', 'News Feed'), ('EVENTS', 'Events Display'), ('FACULTY', 'Faculty Grid'), ('VIDEO', 'Video Section')], default='TEXT', max_length=30),
        ),
    ]
