# Generated by Django 5.1.4 on 2026-01-17 01:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_section_section_type'),
        ('tenants', '0010_add_icon_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebsiteInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(default='My School Website', max_length=200)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('subdomain', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('font_family', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cms/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='cms/favicons/')),
                ('custom_structure', models.JSONField(default=dict, help_text="Tenant's customized pages & sections")),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('visitor_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_instances', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'cms_tenant_website_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='website',
            name='template_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_websites', to='cms.tenantwebsiteinstance'),
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('vibrant', 'Vibrant'), ('professional', 'Professional')], default='modern', max_length=20)),
                ('thumbnail', models.TextField(blank=True, help_text='CSS gradient or image URL')),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('secondary_color', models.CharField(default='#1e40af', max_length=20)),
                ('accent_color', models.CharField(default='#60a5fa', max_length=20)),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100)),
                ('structure', models.JSONField(default=dict, help_text='JSON structure with pages and sections')),
                ('is_system', models.BooleanField(default=True, help_text='System templates cannot be modified')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for system templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_website_templates',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tenantwebsiteinstance',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Original template this was forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='cms.websitetemplate'),
        ),
    ]
