# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of the class')),
                ('end_time', models.TimeField(help_text='End time of the class')),
                ('room', models.CharField(blank=True, help_text='Room number or location', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slot is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions')),
                ('period_number', models.IntegerField(blank=True, help_text='Period number in the daily schedule', null=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this timetable slot', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='tenants.academicyear')),
                ('section', models.ForeignKey(help_text='Section/Class for this slot', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='tenants.section')),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='tenants.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher assigned to this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'db_table': 'timetable_slots',
                'ordering': ['day_of_week', 'start_time', 'period_number'],
                'indexes': [models.Index(fields=['tenant', 'academic_year', 'section'], name='timetable_s_tenant__4b6e32_idx'), models.Index(fields=['tenant', 'teacher', 'day_of_week'], name='timetable_s_tenant__699082_idx'), models.Index(fields=['tenant', 'day_of_week', 'start_time'], name='timetable_s_tenant__58dbbe_idx'), models.Index(fields=['room', 'day_of_week', 'start_time'], name='timetable_s_room_5f5287_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time')],
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template')),
                ('academic_year', models.ForeignKey(help_text='Academic year this template is for', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Timetable Template',
                'verbose_name_plural': 'Timetable Templates',
                'db_table': 'timetable_templates',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name', 'academic_year'), name='unique_template_name_per_year')],
            },
        ),
    ]
