# Generated by Django 5.1.4 on 2026-01-27 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_initial'),
        ('tenants', '0005_merge_20260124_1812'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSectionLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('periods_per_week', models.PositiveIntegerField(default=1, help_text='Number of periods for this subject per week')),
                ('room_preference', models.CharField(blank=True, help_text='Preferred room or room type (e.g., "Lab", "Room 101")', max_length=100)),
                ('max_periods_per_day', models.PositiveIntegerField(default=2, help_text='Maximum periods of this subject allowed per day')),
                ('requires_lab', models.BooleanField(default=False, help_text='Whether this subject requires a lab/special room')),
                ('priority', models.PositiveIntegerField(default=5, help_text='Scheduling priority (1=highest, 10=lowest). Higher priority subjects are scheduled first.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this load is active for scheduling')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this load configuration', on_delete=django.db.models.deletion.CASCADE, related_name='subject_section_loads', to='tenants.academicyear')),
                ('preferred_teacher', models.ForeignKey(blank=True, help_text='Preferred teacher for this subject-section combination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_subject_loads', to='staff.staff')),
                ('section', models.ForeignKey(help_text='Section/Class this load applies to', on_delete=django.db.models.deletion.CASCADE, related_name='subject_loads', to='tenants.section')),
                ('subject', models.ForeignKey(help_text='Subject to be scheduled', on_delete=django.db.models.deletion.CASCADE, related_name='section_loads', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Subject Section Load',
                'verbose_name_plural': 'Subject Section Loads',
                'db_table': 'timetable_subject_section_loads',
                'ordering': ['section', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'academic_year', 'section', 'subject'), name='unique_subject_section_load')],
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(default='Default Schedule', help_text='Configuration name (e.g., "Regular Schedule", "Exam Schedule")', max_length=100)),
                ('working_days', models.JSONField(default=list, help_text='Days when school operates as JSON array: ["MONDAY", "TUESDAY", ...]')),
                ('periods', models.JSONField(default=list, help_text='Period timings as JSON array: [{"period": 1, "start": "08:00", "end": "08:45", "type": "class"}, ...]')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('academic_year', models.ForeignKey(help_text='Academic year this configuration is for', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_period_configs', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Period Configuration',
                'verbose_name_plural': 'Period Configurations',
                'db_table': 'timetable_period_configs',
                'ordering': ['-is_active', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'academic_year', 'name'), name='unique_period_config_name_per_year')],
            },
        ),
    ]
