# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('access_code', models.CharField(help_text='Unique access code for parent', max_length=50, unique=True)),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether access is active')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login time', null=True)),
            ],
            options={
                'verbose_name': 'Admission Portal Access',
                'verbose_name_plural': 'Admission Portal Access',
                'db_table': 'admission_portal_access',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('lead_number', models.CharField(help_text='Unique lead number', max_length=50, unique=True)),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('WEBSITE', 'Website Form'), ('REFERRAL', 'Referral'), ('SOCIAL_MEDIA', 'Social Media'), ('EDUCATION_FAIR', 'Education Fair'), ('PHONE_CALL', 'Phone Call'), ('EMAIL', 'Email'), ('OTHER', 'Other')], help_text='Lead source', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CAMPUS_VISIT', 'Campus Visit Scheduled'), ('VISITED', 'Visited Campus'), ('APPLICATION_RECEIVED', 'Application Received'), ('SHORTLISTED', 'Shortlisted'), ('ADMITTED', 'Admitted'), ('LOST', 'Lost')], default='NEW', help_text='Lead status', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Lead priority', max_length=20)),
                ('student_name', models.CharField(help_text='Prospective student name', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, help_text='Student date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('current_school', models.CharField(blank=True, help_text='Current school (if any)', max_length=200)),
                ('parent_name', models.CharField(help_text='Parent/Guardian name', max_length=200)),
                ('parent_email', models.EmailField(help_text='Parent email', max_length=254)),
                ('parent_phone', models.CharField(help_text='Parent phone', max_length=20)),
                ('parent_alternate_phone', models.CharField(blank=True, help_text='Alternate phone', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('next_follow_up', models.DateTimeField(blank=True, help_text='Next follow-up date/time', null=True)),
                ('follow_up_notes', models.TextField(blank=True, help_text='Follow-up notes')),
                ('application_fee_paid', models.BooleanField(default=False, help_text='Whether application fee is paid')),
                ('application_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Application fee amount', max_digits=10, null=True)),
                ('application_fee_payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=200)),
                ('documents_submitted', models.BooleanField(default=False, help_text='Whether documents are submitted')),
                ('converted_to_student', models.BooleanField(default=False, help_text='Whether converted to student')),
                ('converted_at', models.DateTimeField(blank=True, help_text='When converted to student', null=True)),
                ('lost_reason', models.TextField(blank=True, help_text='Reason for losing the lead')),
                ('lost_at', models.DateTimeField(blank=True, help_text='When lead was lost', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PREVIOUS_MARKSHEET', 'Previous Marksheet'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('PHOTO', 'Photograph'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('OTHER', 'Other')], help_text='Type of document', max_length=50)),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('file', models.FileField(help_text='Document file', upload_to='crm/documents/%Y/%m/')),
                ('uploaded_by', models.CharField(blank=True, help_text='Who uploaded (parent/staff)', max_length=200)),
                ('verified', models.BooleanField(default=False, help_text='Whether document is verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When verified', null=True)),
            ],
            options={
                'verbose_name': 'Lead Document',
                'verbose_name_plural': 'Lead Documents',
                'db_table': 'lead_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('CAMPUS_VISIT', 'Campus Visit'), ('NOTE', 'Note'), ('OTHER', 'Other')], help_text='Type of interaction', max_length=50)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When interaction occurred')),
                ('subject', models.CharField(blank=True, help_text='Interaction subject', max_length=500)),
                ('notes', models.TextField(help_text='Interaction notes/details')),
                ('outcome', models.CharField(blank=True, help_text='Outcome of interaction', max_length=200)),
                ('next_action', models.TextField(blank=True, help_text='Next action to take')),
                ('next_action_date', models.DateTimeField(blank=True, help_text='When to take next action', null=True)),
            ],
            options={
                'verbose_name': 'Lead Interaction',
                'verbose_name_plural': 'Lead Interactions',
                'db_table': 'lead_interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('visitor_number', models.CharField(help_text='Unique visitor number', max_length=50)),
                ('name', models.CharField(help_text='Visitor name', max_length=200)),
                ('phone', models.CharField(help_text='Visitor phone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Visitor email', max_length=254)),
                ('organization', models.CharField(blank=True, help_text='Organization/Company', max_length=200)),
                ('purpose', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('ADMISSION', 'Admission'), ('PARENT_MEETING', 'Parent Meeting'), ('VENDOR', 'Vendor'), ('GUEST', 'Guest'), ('INTERVIEW', 'Interview'), ('OTHER', 'Other')], help_text='Purpose of visit', max_length=50)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Check-in time')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Check-out time', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Visitor photo (webcam capture)', null=True, upload_to='crm/visitors/%Y/%m/')),
                ('badge_number', models.CharField(blank=True, help_text='Visitor badge number', max_length=50)),
                ('badge_printed', models.BooleanField(default=False, help_text='Whether badge was printed')),
                ('notes', models.TextField(blank=True, help_text='Visit notes')),
                ('feedback', models.TextField(blank=True, help_text='Visitor feedback')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'visitors',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
