# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionportalaccess',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='lead',
            name='grade_applying_for',
            field=models.ForeignKey(blank=True, help_text='Grade applying for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Converted student record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_source', to='students.student'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='admissionportalaccess',
            name='lead',
            field=models.OneToOneField(help_text='Related lead', on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='lead',
            field=models.ForeignKey(help_text='Related lead', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff who verified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='lead',
            field=models.ForeignKey(help_text='Related lead', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='staff',
            field=models.ForeignKey(help_text='Staff who had the interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interactions', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Related lead (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='meeting_with',
            field=models.ForeignKey(blank=True, help_text='Staff to meet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_meetings', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status'], name='leads_tenant__ffb606_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='leads_source_805dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_assigne_c5180e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up'], name='leads_next_fo_9ca5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['tenant', 'lead'], name='lead_intera_tenant__41f11e_idx'),
        ),
        migrations.AddIndex(
            model_name='leadinteraction',
            index=models.Index(fields=['interaction_date'], name='lead_intera_interac_395f50_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['tenant', 'check_in_time'], name='visitors_tenant__ae92ea_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['purpose'], name='visitors_purpose_058038_idx'),
        ),
    ]
