# Generated by Django 5.1.4 on 2025-12-27 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('widget_id', models.SlugField(help_text='Unique widget identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Widget display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Widget description')),
                ('component_name', models.CharField(help_text='Frontend component name (e.g., FeeTrendChart)', max_length=100)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('attendance', 'Attendance'), ('communication', 'Communication'), ('analytics', 'Analytics'), ('system', 'System')], db_index=True, help_text='Widget category', max_length=50)),
                ('available_for_roles', models.JSONField(default=list, help_text='List of role codes that can use this widget (e.g., ["principal", "teacher"])')),
                ('required_permissions', models.JSONField(default=list, help_text='List of required permissions (e.g., ["student_module.read"])')),
                ('default_width', models.IntegerField(default=2, help_text='Default width in grid units')),
                ('default_height', models.IntegerField(default=2, help_text='Default height in grid units')),
                ('min_width', models.IntegerField(default=1, help_text='Minimum width in grid units')),
                ('min_height', models.IntegerField(default=1, help_text='Minimum height in grid units')),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema for widget configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this widget is available')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in widget library')),
            ],
            options={
                'verbose_name': 'Widget Definition',
                'verbose_name_plural': 'Widget Definitions',
                'db_table': 'widget_definitions',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('layout', models.JSONField(default=list, help_text='Widget layout configuration')),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='When layout was last modified')),
                ('user', models.OneToOneField(help_text='User this layout belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Layout',
                'verbose_name_plural': 'Dashboard Layouts',
                'db_table': 'dashboard_layouts',
            },
        ),
    ]
