# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('staff', '0002_initial'),
        ('students', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlayout',
            name='user',
            field=models.OneToOneField(help_text='User this layout belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='class_filter',
            field=models.ForeignKey(blank=True, help_text='Filter by class (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboards', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='section_filter',
            field=models.ForeignKey(blank=True, help_text='Filter by section (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboards', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.leaderboard'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section for class rankings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='students.student'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentdashboardconfig',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='roledefaultlayout',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_cache', to='dashboard.widgetdefinition'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard', 'rank'], name='leaderboard_leaderb_bb9735_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['leaderboard', 'period_start', 'period_end'], name='leaderboard_leaderb_fc668e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['student', 'leaderboard'], name='leaderboard_student_70901c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['staff', 'leaderboard'], name='leaderboard_staff_i_1f5da2_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentdashboardconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'is_active'), name='unique_active_parent_dashboard'),
        ),
        migrations.AddConstraint(
            model_name='roledefaultlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'role_code', 'is_active'), name='unique_active_layout_per_role'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together={('tenant', 'widget', 'filters')},
        ),
    ]
