import os
import django

os.environ["DJANGO_SETTINGS_MODULE"] = "config.settings.dev"
django.setup()

from django.db import connection

sql1 = """
CREATE TABLE IF NOT EXISTS parent_users (
    id uuid NOT NULL PRIMARY KEY,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp with time zone NULL,
    relation_type varchar(20) NOT NULL,
    occupation varchar(200) NOT NULL DEFAULT '',
    office_address text NOT NULL DEFAULT '',
    preferred_language varchar(10) NOT NULL DEFAULT 'en',
    email_notifications boolean NOT NULL DEFAULT true,
    sms_notifications boolean NOT NULL DEFAULT true,
    push_notifications boolean NOT NULL DEFAULT true,
    portal_access_enabled boolean NOT NULL DEFAULT true,
    last_login_at timestamp with time zone NULL,
    user_id integer NULL,
    tenant_id uuid NULL
)
"""

sql2 = """
CREATE TABLE IF NOT EXISTS parent_users_students (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parentuser_id uuid NOT NULL,
    student_id uuid NOT NULL
)
"""

try:
    with connection.cursor() as cursor:
        cursor.execute(sql1)
        print("Created parent_users table")
        cursor.execute(sql2)
        print("Created parent_users_students table")
    print("SUCCESS!")
except Exception as e:
    print(f"ERROR: {e}")