# Generated by Django 5.1.4 on 2025-12-30 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Term name (e.g., "Mid-Term 2024")', max_length=100)),
                ('term_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('MID_TERM', 'Mid-Term'), ('FINAL', 'Final'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('ANNUAL', 'Annual'), ('ENTRANCE', 'Entrance'), ('OTHER', 'Other')], help_text='Type of exam term', max_length=20)),
                ('start_date', models.DateField(help_text='Term start date')),
                ('end_date', models.DateField(help_text='Term end date')),
                ('description', models.TextField(blank=True, help_text='Term description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this term is active')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this term', on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Exam Term',
                'verbose_name_plural': 'Exam Terms',
                'db_table': 'exam_terms',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Exam name', max_length=200)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, help_text='Total marks for this exam', max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40.0, help_text='Minimum passing marks', max_digits=6)),
                ('duration_minutes', models.IntegerField(help_text='Exam duration in minutes')),
                ('instructions', models.TextField(blank=True, help_text='Exam instructions for students')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Exam status', max_length=20)),
                ('syllabus', models.TextField(blank=True, help_text='Syllabus/topics covered')),
                ('question_paper', models.FileField(blank=True, help_text='Question paper file', null=True, upload_to='exams/question_papers/%Y/%m/')),
                ('answer_key', models.FileField(blank=True, help_text='Answer key file', null=True, upload_to='exams/answer_keys/%Y/%m/')),
                ('grade_level', models.ForeignKey(help_text='Grade level for this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.gradelevel')),
                ('sections', models.ManyToManyField(help_text='Sections taking this exam', related_name='exams', to='tenants.section')),
                ('subject', models.ForeignKey(help_text='Subject for this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('exam_term', models.ForeignKey(help_text='Exam term this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examterm')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('code', models.CharField(help_text='Outcome code (e.g., LO1, CO1)', max_length=50)),
                ('description', models.TextField(help_text='Learning outcome description')),
                ('bloom_level', models.CharField(blank=True, choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze'), ('EVALUATE', 'Evaluate'), ('CREATE', 'Create')], help_text="Bloom's taxonomy level", max_length=20)),
                ('subject', models.ForeignKey(help_text='Subject for this outcome', on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Learning Outcome',
                'verbose_name_plural': 'Learning Outcomes',
                'db_table': 'learning_outcomes',
                'ordering': ['subject', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Topic name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Topic description')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('grade_level', models.ForeignKey(help_text='Grade level for this topic', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tenants.gradelevel')),
                ('subject', models.ForeignKey(help_text='Subject this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topics',
                'ordering': ['subject', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('question_text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_ANSWER', 'Short Answer'), ('LONG_ANSWER', 'Long Answer'), ('FILL_BLANK', 'Fill in the Blank'), ('MATCH', 'Matching'), ('NUMERICAL', 'Numerical'), ('ESSAY', 'Essay')], help_text='Type of question', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], help_text='Question difficulty level', max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, help_text='Marks for this question', max_digits=5)),
                ('option_a', models.TextField(blank=True, help_text='Option A (for MCQ)')),
                ('option_b', models.TextField(blank=True, help_text='Option B (for MCQ)')),
                ('option_c', models.TextField(blank=True, help_text='Option C (for MCQ)')),
                ('option_d', models.TextField(blank=True, help_text='Option D (for MCQ)')),
                ('correct_answer', models.TextField(blank=True, help_text='Correct answer or answer key')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('image', models.ImageField(blank=True, help_text='Question image (if any)', null=True, upload_to='questions/images/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this question has been used')),
                ('learning_outcome', models.ForeignKey(blank=True, help_text='Associated learning outcome (for OBE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.learningoutcome')),
                ('subject', models.ForeignKey(help_text='Subject for this question', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('topic', models.ForeignKey(help_text='Topic for this question', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question Bank',
                'db_table': 'question_bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Related topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_outcomes', to='exams.topic'),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('exam_date', models.DateField(help_text='Date of exam')),
                ('start_time', models.TimeField(help_text='Exam start time')),
                ('end_time', models.TimeField(help_text='Exam end time')),
                ('room', models.CharField(blank=True, help_text='Exam room/venue', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('exam', models.ForeignKey(help_text='Exam being scheduled', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam')),
                ('invigilator', models.ForeignKey(blank=True, help_text='Invigilator for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='staff.staff')),
                ('section', models.ForeignKey(help_text='Section taking this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='tenants.section')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'db_table': 'exam_schedules',
                'ordering': ['exam_date', 'start_time'],
                'indexes': [models.Index(fields=['tenant', 'exam_date', 'start_time'], name='exam_schedu_tenant__76f58d_idx'), models.Index(fields=['section', 'exam_date'], name='exam_schedu_section_e0fbee_idx'), models.Index(fields=['room', 'exam_date', 'start_time'], name='exam_schedu_room_8f1d19_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'section'), name='unique_exam_section_schedule'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time_exam')],
            },
        ),
        migrations.AddIndex(
            model_name='examterm',
            index=models.Index(fields=['tenant', 'academic_year', 'is_active'], name='exam_terms_tenant__c1dd81_idx'),
        ),
        migrations.AddIndex(
            model_name='examterm',
            index=models.Index(fields=['term_type', 'start_date'], name='exam_terms_term_ty_ef8b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'exam_term', 'status'], name='exams_tenant__2f393f_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'grade_level'], name='exams_subject_61b352_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['tenant', 'subject', 'grade_level'], name='topics_tenant__984669_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['tenant', 'subject', 'topic'], name='question_ba_tenant__1ed78e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['difficulty', 'question_type'], name='question_ba_difficu_741a00_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_active', 'subject'], name='question_ba_is_acti_8aa106_idx'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['tenant', 'subject'], name='learning_ou_tenant__0562d2_idx'),
        ),
    ]
