# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade_level',
            field=models.ForeignKey(help_text='Grade level for this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sections',
            field=models.ManyToManyField(help_text='Sections taking this exam', related_name='exams', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
    ]
