# Generated by Django 5.1.4 on 2025-12-31 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Configuration name (e.g., "Standard Grading")', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default configuration')),
                ('description', models.TextField(blank=True, help_text='Configuration description')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='grade_configurations', to='tenants.academicyear')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grade Configuration',
                'verbose_name_plural': 'Grade Configurations',
                'db_table': 'grade_configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('grade', models.CharField(help_text='Grade (e.g., A+, A, B+)', max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Minimum percentage for this grade', max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, help_text='Maximum percentage for this grade', max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='Grade point (e.g., 4.0 for A+)', max_digits=4)),
                ('remarks', models.CharField(blank=True, help_text='Remarks (e.g., "Excellent", "Good")', max_length=100)),
                ('configuration', models.ForeignKey(help_text='Grade configuration this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='exams.gradeconfiguration')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'db_table': 'grade_scales',
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks obtained by student', max_digits=6)),
                ('grade', models.CharField(blank=True, help_text='Grade (auto-calculated)', max_length=10)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='Grade point (auto-calculated)', max_digits=4, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (auto-calculated)', max_digits=5, null=True)),
                ('is_pass', models.BooleanField(default=False, help_text='Whether student passed')),
                ('is_absent', models.BooleanField(default=False, help_text='Whether student was absent')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('WITHHELD', 'Withheld')], default='DRAFT', help_text='Result status', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Remarks/comments')),
                ('published_at', models.DateTimeField(blank=True, help_text='When result was published', null=True)),
                ('entered_by', models.ForeignKey(help_text='User who entered this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(help_text='Exam for this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('section', models.ForeignKey(help_text='Section', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='tenants.section')),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'db_table': 'exam_results',
                'ordering': ['exam', 'section', 'student'],
                'indexes': [models.Index(fields=['tenant', 'exam', 'section'], name='exam_result_tenant__b00ed3_idx'), models.Index(fields=['student', 'exam'], name='exam_result_student_520be3_idx'), models.Index(fields=['status', 'is_pass'], name='exam_result_status_329e03_idx')],
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_student_result')],
            },
        ),
        migrations.AddIndex(
            model_name='gradeconfiguration',
            index=models.Index(fields=['tenant', 'academic_year', 'is_default'], name='grade_confi_tenant__1c8c33_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['tenant', 'configuration'], name='grade_scale_tenant__df8c86_idx'),
        ),
    ]
