# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('staff', '0002_initial'),
        ('students', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='entered_by',
            field=models.ForeignKey(help_text='User who entered this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(help_text='Exam for this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='section',
            field=models.ForeignKey(help_text='Section', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam',
            field=models.ForeignKey(help_text='Exam being scheduled', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='invigilator',
            field=models.ForeignKey(blank=True, help_text='Invigilator for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='section',
            field=models.ForeignKey(help_text='Section taking this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for this term', on_delete=django.db.models.deletion.CASCADE, related_name='exam_terms', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='examterm',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_term',
            field=models.ForeignKey(help_text='Exam term this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.examterm'),
        ),
        migrations.AddField(
            model_name='gradeconfiguration',
            name='academic_year',
            field=models.ForeignKey(help_text='Academic year for this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='grade_configurations', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='gradeconfiguration',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='configuration',
            field=models.ForeignKey(help_text='Grade configuration this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='exams.gradeconfiguration'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this outcome', on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Related offline exam (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='grade_level',
            field=models.ForeignKey(help_text='Grade level for this online exam', on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='sections',
            field=models.ManyToManyField(help_text='Sections eligible for this exam', related_name='online_exams', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this online exam', on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='onlineexamanswer',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='onlineexamsession',
            name='online_exam',
            field=models.ForeignKey(help_text='Online exam', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.onlineexam'),
        ),
        migrations.AddField(
            model_name='onlineexamsession',
            name='student',
            field=models.ForeignKey(help_text='Student taking the exam', on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_sessions', to='students.student'),
        ),
        migrations.AddField(
            model_name='onlineexamsession',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='onlineexamanswer',
            name='session',
            field=models.ForeignKey(help_text='Exam session', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.onlineexamsession'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, help_text='Associated learning outcome (for OBE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.learningoutcome'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(help_text='Subject for this question', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='onlineexamanswer',
            name='question',
            field=models.ForeignKey(help_text='Question', on_delete=django.db.models.deletion.CASCADE, related_name='online_answers', to='exams.questionbank'),
        ),
        migrations.AddField(
            model_name='onlineexam',
            name='questions',
            field=models.ManyToManyField(help_text='Questions included in this exam', related_name='online_exams', to='exams.questionbank'),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade_level',
            field=models.ForeignKey(help_text='Grade level for this topic', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(help_text='Subject this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='tenants.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic',
            field=models.ForeignKey(help_text='Topic for this question', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Related topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_outcomes', to='exams.topic'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['tenant', 'exam', 'section'], name='exam_result_tenant__b00ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'exam'], name='exam_result_student_520be3_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['status', 'is_pass'], name='exam_result_status_329e03_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_student_result'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['tenant', 'exam_date', 'start_time'], name='exam_schedu_tenant__76f58d_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['section', 'exam_date'], name='exam_schedu_section_e0fbee_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['room', 'exam_date', 'start_time'], name='exam_schedu_room_8f1d19_idx'),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('exam', 'section'), name='unique_exam_section_schedule'),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time_exam'),
        ),
        migrations.AddIndex(
            model_name='examterm',
            index=models.Index(fields=['tenant', 'academic_year', 'is_active'], name='exam_terms_tenant__c1dd81_idx'),
        ),
        migrations.AddIndex(
            model_name='examterm',
            index=models.Index(fields=['term_type', 'start_date'], name='exam_terms_term_ty_ef8b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['tenant', 'exam_term', 'status'], name='exams_tenant__2f393f_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'grade_level'], name='exams_subject_61b352_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeconfiguration',
            index=models.Index(fields=['tenant', 'academic_year', 'is_default'], name='grade_confi_tenant__1c8c33_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['tenant', 'configuration'], name='grade_scale_tenant__df8c86_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamsession',
            index=models.Index(fields=['tenant', 'online_exam', 'status'], name='online_exam_tenant__bbf1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamsession',
            index=models.Index(fields=['student', 'status'], name='online_exam_student_2d0d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlineexamsession',
            constraint=models.UniqueConstraint(fields=('online_exam', 'student'), name='unique_online_exam_student_session'),
        ),
        migrations.AddIndex(
            model_name='onlineexamanswer',
            index=models.Index(fields=['tenant', 'session'], name='online_exam_tenant__b93de6_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamanswer',
            index=models.Index(fields=['question', 'is_correct'], name='online_exam_questio_993a37_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlineexamanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_session_question_answer'),
        ),
        migrations.AddIndex(
            model_name='onlineexam',
            index=models.Index(fields=['tenant', 'status', 'start_datetime'], name='online_exam_tenant__f12a64_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexam',
            index=models.Index(fields=['subject', 'grade_level'], name='online_exam_subject_536a32_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['tenant', 'subject', 'grade_level'], name='topics_tenant__984669_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['tenant', 'subject', 'topic'], name='question_ba_tenant__1ed78e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['difficulty', 'question_type'], name='question_ba_difficu_741a00_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_active', 'subject'], name='question_ba_is_acti_8aa106_idx'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['tenant', 'subject'], name='learning_ou_tenant__0562d2_idx'),
        ),
    ]
