# Generated by Django 5.2.9 on 2026-01-04 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_gradeconfiguration_gradescale_examresult_and_more'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0005_tenantsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Online exam name', max_length=200)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks for this exam', max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, help_text='Minimum passing marks', max_digits=6)),
                ('duration_minutes', models.IntegerField(help_text='Exam duration in minutes')),
                ('start_datetime', models.DateTimeField(help_text='Exam start date and time')),
                ('end_datetime', models.DateTimeField(help_text='Exam end date and time')),
                ('instructions', models.TextField(blank=True, help_text='Exam instructions for students')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Exam status', max_length=20)),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Shuffle question order for each student')),
                ('shuffle_options', models.BooleanField(default=True, help_text='Shuffle MCQ options for each student')),
                ('show_results_immediately', models.BooleanField(default=False, help_text='Show results to student immediately after submission')),
                ('allow_review', models.BooleanField(default=True, help_text='Allow students to review answers before submission')),
                ('proctoring_level', models.CharField(choices=[('NONE', 'No Proctoring'), ('BASIC', 'Basic (Tab Switch Detection)'), ('ADVANCED', 'Advanced (Webcam + Screen Recording)')], default='BASIC', help_text='Proctoring level', max_length=20)),
                ('max_tab_switches', models.IntegerField(default=3, help_text='Maximum allowed tab switches before auto-submit')),
                ('auto_submit_on_time_end', models.BooleanField(default=True, help_text='Auto-submit exam when time expires')),
                ('exam', models.ForeignKey(blank=True, help_text='Related offline exam (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='exams.exam')),
                ('grade_level', models.ForeignKey(help_text='Grade level for this online exam', on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='tenants.gradelevel')),
                ('questions', models.ManyToManyField(help_text='Questions included in this exam', related_name='online_exams', to='exams.questionbank')),
                ('sections', models.ManyToManyField(help_text='Sections eligible for this exam', related_name='online_exams', to='tenants.section')),
                ('subject', models.ForeignKey(help_text='Subject for this online exam', on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='tenants.subject')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Online Exam',
                'verbose_name_plural': 'Online Exams',
                'db_table': 'online_exams',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When student started the exam')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When student submitted the exam', null=True)),
                ('time_remaining_seconds', models.IntegerField(blank=True, help_text='Time remaining when submitted (in seconds)', null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('TERMINATED', 'Terminated')], default='STARTED', help_text='Session status', max_length=20)),
                ('tab_switch_count', models.IntegerField(default=0, help_text='Number of times student switched tabs')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of student', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Total score obtained', max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage scored', max_digits=5, null=True)),
                ('is_pass', models.BooleanField(default=False, help_text='Whether student passed')),
                ('proctoring_violations', models.JSONField(blank=True, default=list, help_text='List of proctoring violations')),
                ('online_exam', models.ForeignKey(help_text='Online exam', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.onlineexam')),
                ('student', models.ForeignKey(help_text='Student taking the exam', on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_sessions', to='students.student')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Online Exam Session',
                'verbose_name_plural': 'Online Exam Sessions',
                'db_table': 'online_exam_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExamAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('answer_text', models.TextField(blank=True, help_text='Student answer (for text-based questions)')),
                ('selected_option', models.CharField(blank=True, help_text='Selected option (A, B, C, D for MCQ)', max_length=10)),
                ('is_correct', models.BooleanField(default=False, help_text='Whether answer is correct (auto-calculated for MCQ)')),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0.0, help_text='Marks awarded (for manual grading)', max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now=True, help_text='When answer was last updated')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this question (in seconds)')),
                ('is_marked_for_review', models.BooleanField(default=False, help_text='Whether student marked this for review')),
                ('question', models.ForeignKey(help_text='Question', on_delete=django.db.models.deletion.CASCADE, related_name='online_answers', to='exams.questionbank')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('session', models.ForeignKey(help_text='Exam session', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.onlineexamsession')),
            ],
            options={
                'verbose_name': 'Online Exam Answer',
                'verbose_name_plural': 'Online Exam Answers',
                'db_table': 'online_exam_answers',
                'ordering': ['session', 'question'],
            },
        ),
        migrations.AddIndex(
            model_name='onlineexam',
            index=models.Index(fields=['tenant', 'status', 'start_datetime'], name='online_exam_tenant__f12a64_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexam',
            index=models.Index(fields=['subject', 'grade_level'], name='online_exam_subject_536a32_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamsession',
            index=models.Index(fields=['tenant', 'online_exam', 'status'], name='online_exam_tenant__bbf1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamsession',
            index=models.Index(fields=['student', 'status'], name='online_exam_student_2d0d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlineexamsession',
            constraint=models.UniqueConstraint(fields=('online_exam', 'student'), name='unique_online_exam_student_session'),
        ),
        migrations.AddIndex(
            model_name='onlineexamanswer',
            index=models.Index(fields=['tenant', 'session'], name='online_exam_tenant__b93de6_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineexamanswer',
            index=models.Index(fields=['question', 'is_correct'], name='online_exam_questio_993a37_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlineexamanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_session_question_answer'),
        ),
    ]
