# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('staff', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='finance.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='finance.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='ledgeraccount',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('budget', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='salarypayment',
            unique_together={('staff', 'month')},
        ),
    ]
