// Centralized options for forms
export const citizenshipOptions = [
    // Priority countries on top
    'India',
    'United States',
    'United Kingdom',
    'Canada',
    'Australia',
    'Singapore',
    'United Arab Emirates',
    'Saudi Arabia',
    'Other',
    // Remaining countries (alphabetical-ish)
    'Afghanistan',
    'Albania',
    'Algeria',
    'Argentina',
    'Austria',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Bhutan',
    'Brazil',
    'China',
    'Colombia',
    'Denmark',
    'Egypt',
    'Finland',
    'France',
    'Germany',
    'Ghana',
    'Greece',
    'Indonesia',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Japan',
    'Jordan',
    'Kenya',
    'Malaysia',
    'Maldives',
    'Mexico',
    'Morocco',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nigeria',
    'Norway',
    'Pakistan',    
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Russia',
    'South Africa',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'Sweden',
    'Switzerland',
    'Thailand',
    'Turkey',
    'Vietnam',
];

export const religionOptions = [
    'Hindu',
    'Muslim',
    'Christian',
    'Sikh',
    'Buddhist',
    'Jain',
    'Other',
];

export default {
    citizenshipOptions,
    religionOptions,
};
