# Generated by Django 5.1.4 on 2025-12-28 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('student_cutoff_time', models.TimeField(default='10:00:00', help_text='Auto-absent cutoff time for students')),
                ('student_late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after which student is marked late')),
                ('staff_cutoff_time', models.TimeField(default='09:00:00', help_text='Auto-absent cutoff time for staff')),
                ('staff_shift_start_time', models.TimeField(default='08:30:00', help_text='Staff shift start time')),
                ('staff_late_buffer_minutes', models.IntegerField(default=10, help_text='Buffer minutes before marking staff late')),
                ('late_marks_for_half_day', models.IntegerField(default=3, help_text='Number of late marks equals one half day')),
                ('consecutive_absents_alert', models.IntegerField(default=3, help_text='Alert after N consecutive absents')),
                ('enable_monthly_whatsapp_reports', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'db_table': 'attendance_configuration',
            },
        ),
        migrations.CreateModel(
            name='AttendanceMonthlyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('record_type', models.CharField(max_length=10)),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_days', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='attendance/reports/')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.academicyear')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_aggregates', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_aggregates', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_aggregates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Monthly Attendance Aggregate',
                'db_table': 'attendance_monthly_aggregates',
            },
        ),
        migrations.CreateModel(
            name='QRCodeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('valid_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='staff.staff')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'qr_code_tokens',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('record_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], max_length=20)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('QR_CODE', 'QR Code Scan'), ('FACE', 'Face Recognition'), ('RFID', 'RFID Card'), ('BIOMETRIC', 'Biometric'), ('GEO_TAG', 'Geo Tagging'), ('AUTO', 'Auto-Marked')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_event_day', models.BooleanField(default=False, help_text='Marked on event/non-instructional day')),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.academicyear')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universal_attendance_records', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'record_type'], name='attendance__date_f1f657_idx'), models.Index(fields=['academic_year', 'record_type'], name='attendance__academi_67d52d_idx')],
            },
        ),
    ]
