# Generated by Django 5.1.4 on 2026-01-19 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('school_start_time', models.TimeField(default='08:30:00', help_text='School start time for students')),
                ('late_threshold_time', models.TimeField(default='09:30:00', help_text='Time after which students are marked as late')),
                ('student_cutoff_time', models.TimeField(default='10:00:00', help_text='Auto-absent cutoff time for students')),
                ('student_late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after which student is marked late')),
                ('staff_cutoff_time', models.TimeField(default='09:00:00', help_text='Auto-absent cutoff time for staff')),
                ('staff_shift_start_time', models.TimeField(default='08:30:00', help_text='Staff shift start time')),
                ('staff_late_buffer_minutes', models.IntegerField(default=10, help_text='Buffer minutes before marking staff late')),
                ('late_marks_for_half_day', models.IntegerField(default=3, help_text='Number of late marks equals one half day')),
                ('consecutive_absents_alert', models.IntegerField(default=3, help_text='Alert after N consecutive absents')),
                ('enable_monthly_whatsapp_reports', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'db_table': 'attendance_configuration',
            },
        ),
        migrations.CreateModel(
            name='AttendanceMonthlyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('record_type', models.CharField(max_length=10)),
                ('month', models.DateField(help_text='First day of the month')),
                ('total_days', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='attendance/reports/')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Monthly Attendance Aggregate',
                'db_table': 'attendance_monthly_aggregates',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('record_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], max_length=20)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('QR_CODE', 'QR Code Scan'), ('FACE', 'Face Recognition'), ('RFID', 'RFID Card'), ('BIOMETRIC', 'Biometric'), ('GEO_TAG', 'Geo Tagging'), ('AUTO', 'Auto-Marked')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_event_day', models.BooleanField(default=False, help_text='Marked on event/non-instructional day')),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('valid_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'qr_code_tokens',
            },
        ),
        migrations.CreateModel(
            name='StudentFaceEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('encoding_data', models.JSONField(help_text='Face encoding vector as JSON array')),
                ('reference_image', models.ImageField(blank=True, help_text='Reference image used for face encoding', null=True, upload_to='students/face_encodings/')),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score of the face encoding (0-1)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Student Face Encoding',
                'verbose_name_plural': 'Student Face Encodings',
                'db_table': 'student_face_encodings',
            },
        ),
    ]
