# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceconfiguration',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_config', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attendancemonthlyaggregate',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='attendancemonthlyaggregate',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_aggregates', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='attendancemonthlyaggregate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_aggregates', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendancemonthlyaggregate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_aggregates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.academicyear'),
        ),
    ]
