# Generated by Django 5.2.9 on 2026-01-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceconfiguration',
            name='late_threshold_time',
            field=models.TimeField(default='09:30:00', help_text='Time after which students are marked as late'),
        ),
        migrations.AddField(
            model_name='attendanceconfiguration',
            name='school_start_time',
            field=models.TimeField(default='08:30:00', help_text='School start time for students'),
        ),
    ]
