# Generated by Django 5.2.9 on 2026-01-07 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendanceconfiguration_late_threshold_time_and_more'),
        ('students', '0007_remove_historicalstudent_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceEncoding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('encoding_data', models.JSONField(help_text='Face encoding vector as JSON array')),
                ('reference_image', models.ImageField(blank=True, help_text='Reference image used for face encoding', null=True, upload_to='students/face_encodings/')),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score of the face encoding (0-1)')),
                ('is_active', models.BooleanField(default=True)),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Face Encoding',
                'verbose_name_plural': 'Student Face Encodings',
                'db_table': 'student_face_encodings',
            },
        ),
    ]
