# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='sent_by',
            field=models.ForeignKey(help_text='Staff who sent this broadcast', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to='staff.staff'),
        ),
    ]
