# Generated by Django 5.2.9 on 2026-01-15 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_broadcastmessage_deleted_by_and_more'),
        ('staff', '0003_appraisalcycle_deleted_by_staff_deleted_by_and_more'),
        ('tenants', '0010_add_icon_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Event title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('CULTURAL', 'Cultural'), ('SPORTS', 'Sports'), ('MEETING', 'Meeting'), ('EXAM', 'Exam'), ('OTHER', 'Other')], default='OTHER', help_text='Type of event', max_length=20)),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(blank=True, help_text='Event end date (optional for single-day events)', null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Event start time (optional for all-day events)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Event end time (optional)', null=True)),
                ('is_all_day', models.BooleanField(default=True, help_text='Whether this is an all-day event')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=200)),
                ('notify_parents', models.BooleanField(default=False, help_text='Send notification to parents')),
                ('notify_staff', models.BooleanField(default=False, help_text='Send notification to staff')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this event is visible')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(blank=True, help_text='Staff organizing this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='staff.staff')),
                ('target_classes', models.ManyToManyField(blank=True, help_text='Specific classes (leave blank for all)', related_name='school_events', to='tenants.gradelevel')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'School Event',
                'verbose_name_plural': 'School Events',
                'db_table': 'school_events',
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['tenant', 'start_date'], name='school_even_tenant__cf191b_idx'), models.Index(fields=['event_type'], name='school_even_event_t_32da74_idx')],
            },
        ),
    ]
