# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='comm_broadcasts', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='target_sections',
            field=models.ManyToManyField(blank=True, related_name='comm_broadcasts', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='communicationprovider',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
    ]
