# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0003_initial'),
        ('staff', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider',
            field=models.ForeignKey(help_text='Provider used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='communication.communicationprovider'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='communication.messagetemplate'),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template to use', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='communication.messagetemplate'),
        ),
        migrations.AddField(
            model_name='notice',
            name='published_by',
            field=models.ForeignKey(help_text='Staff who published this notice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_notices', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Specific classes (if target is SPECIFIC_CLASS)', related_name='comm_notices', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Specific sections (if target is SPECIFIC_SECTION)', related_name='comm_notices', to='tenants.section'),
        ),
        migrations.AddField(
            model_name='notice',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='notice',
            field=models.ForeignKey(blank=True, help_text='Related notice (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='communication.notice'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='device_token',
            field=models.ForeignKey(blank=True, help_text='Device token used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communication.devicetoken'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Target user (null for topic notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Staff organizing this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='target_classes',
            field=models.ManyToManyField(blank=True, help_text='Specific classes (leave blank for all)', related_name='school_events', to='tenants.gradelevel'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='communicationprovider',
            index=models.Index(fields=['tenant', 'provider_type', 'is_active'], name='communicati_tenant__588c99_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['platform'], name='device_toke_platfor_c289af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user', 'token')},
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['tenant', 'template_type', 'is_active'], name='message_tem_tenant__fa8441_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['tenant', 'status'], name='broadcast_m_tenant__6fd803_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['scheduled_at'], name='broadcast_m_schedul_847619_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['tenant', 'is_published', 'valid_from'], name='notices_tenant__069ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['target_audience'], name='notices_target__9587f1_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['tenant', 'message_type', 'status'], name='message_log_tenant__7f2197_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['recipient_type', 'recipient_id'], name='message_log_recipie_d560bb_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['sent_at'], name='message_log_sent_at_db134d_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['user', 'status'], name='push_notifi_user_id_d4b225_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['notification_type'], name='push_notifi_notific_7f567f_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['sent_at'], name='push_notifi_sent_at_136478_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['tenant', 'start_date'], name='school_even_tenant__cf191b_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolevent',
            index=models.Index(fields=['event_type'], name='school_even_event_t_32da74_idx'),
        ),
    ]
