# Generated by Django 5.1.4 on 2026-01-17 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_add_school_event_model'),
        ('tenants', '0010_add_icon_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('token', models.TextField(help_text='FCM or APNs device token')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], help_text='Device platform', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='Device name/model', max_length=200)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=200)),
                ('app_version', models.CharField(blank=True, help_text='App version on this device', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a notification was sent to this device', null=True)),
                ('subscribed_topics', models.JSONField(default=list, help_text='List of FCM topics this device is subscribed to')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'db_table': 'device_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('body', models.TextField(help_text='Notification body')),
                ('image_url', models.URLField(blank=True, help_text='Notification image URL')),
                ('data_payload', models.JSONField(default=dict, help_text='Additional data sent with notification')),
                ('notification_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('ATTENDANCE', 'Attendance Alert'), ('FEE_REMINDER', 'Fee Reminder'), ('EXAM_RESULT', 'Exam Result'), ('HOMEWORK', 'Homework'), ('EVENT', 'Event'), ('LEAVE', 'Leave Status'), ('GENERAL', 'General')], default='GENERAL', help_text='Type of notification', max_length=50)),
                ('topic', models.CharField(blank=True, help_text='FCM topic (for topic-based notifications)', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', help_text='Notification status', max_length=20)),
                ('fcm_message_id', models.CharField(blank=True, help_text='FCM message ID', max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., "student", "fee_invoice")', max_length=100)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of related object', max_length=100)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('device_token', models.ForeignKey(blank=True, help_text='Device token used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communication.devicetoken')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Target user (null for topic notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['platform'], name='device_toke_platfor_c289af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user', 'token')},
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['user', 'status'], name='push_notifi_user_id_d4b225_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['notification_type'], name='push_notifi_notific_7f567f_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['sent_at'], name='push_notifi_sent_at_136478_idx'),
        ),
    ]
