# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visitor_type', models.CharField(choices=[('PARENT', 'Parent/Guardian'), ('VENDOR', 'Vendor/Supplier'), ('GUEST', 'Guest Speaker'), ('OFFICIAL', 'Government Official'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('id_proof_type', models.CharField(blank=True, help_text='e.g., Aadhar, Passport, Driving License', max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField()),
                ('department_to_visit', models.CharField(blank=True, max_length=100)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('expected_checkout_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('OVERSTAYED', 'Overstayed')], default='CHECKED_IN', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('items_carried', models.TextField(blank=True, help_text='List of items carried (bags, laptops, etc.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/photos/%Y/%m/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='visitors/signatures/%Y/%m/')),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('badge_returned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campus Visitor',
                'verbose_name_plural': 'Campus Visitors',
                'db_table': 'security_campus_visitors',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='CampusVisitorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('action', models.CharField(help_text='e.g., Entered Building A, Met Principal, etc.', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campus Visitor Log',
                'verbose_name_plural': 'Campus Visitor Logs',
                'db_table': 'security_campus_visitor_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'security_gate_logs',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('pass_type', models.CharField(choices=[('EARLY_EXIT', 'Early Exit'), ('VISITOR', 'Visitor Entry'), ('MATERIAL', 'Material Outward')], default='EARLY_EXIT', max_length=20)),
                ('visitor_name', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('USED', 'Used (Exited)')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('token', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'security_gate_passes',
                'ordering': ['-created_at'],
            },
        ),
    ]
