# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusvisitor',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_campus_visitors', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitor',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_campus_visitors', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitor',
            name='person_to_meet',
            field=models.ForeignKey(blank=True, help_text='Staff member being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_visitors', to='staff.staff'),
        ),
    ]
