# Generated by Django 5.2.9 on 2026-01-04 01:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        ('staff', '0002_staffattendance_biometric_device_id_and_more'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0005_tenantsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visitor_type', models.CharField(choices=[('PARENT', 'Parent/Guardian'), ('VENDOR', 'Vendor/Supplier'), ('GUEST', 'Guest Speaker'), ('OFFICIAL', 'Government Official'), ('CONTRACTOR', 'Contractor'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('id_proof_type', models.CharField(blank=True, help_text='e.g., Aadhar, Passport, Driving License', max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField()),
                ('department_to_visit', models.CharField(blank=True, max_length=100)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('expected_checkout_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('OVERSTAYED', 'Overstayed')], default='CHECKED_IN', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('items_carried', models.TextField(blank=True, help_text='List of items carried (bags, laptops, etc.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/photos/%Y/%m/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='visitors/signatures/%Y/%m/')),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('badge_returned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campus Visitor',
                'verbose_name_plural': 'Campus Visitors',
                'db_table': 'security_campus_visitors',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='CampusVisitorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('action', models.CharField(help_text='e.g., Entered Building A, Met Principal, etc.', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campus Visitor Log',
                'verbose_name_plural': 'Campus Visitor Logs',
                'db_table': 'security_campus_visitor_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='gatelog',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='gatelog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['tenant', 'scanned_at'], name='security_ga_tenant__7c7aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['gate_pass', 'action'], name='security_ga_gate_pa_adfa87_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='security_ga_tenant__f71c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['student', 'status'], name='security_ga_student_b10169_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['token'], name='security_ga_token_070716_idx'),
        ),
        migrations.AddField(
            model_name='campusvisitor',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_campus_visitors', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitor',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_campus_visitors', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitor',
            name='person_to_meet',
            field=models.ForeignKey(blank=True, help_text='Staff member being visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_visitors', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitor',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campusvisitorlog',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitorlog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campusvisitorlog',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='security.campusvisitor'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['tenant', 'status', 'check_in_time'], name='security_ca_tenant__6ae7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['phone'], name='security_ca_phone_e07c13_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['person_to_meet', 'check_in_time'], name='security_ca_person__531a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['check_in_time', 'check_out_time'], name='security_ca_check_i_df515e_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitorlog',
            index=models.Index(fields=['tenant', 'visitor', 'timestamp'], name='security_ca_tenant__5e5904_idx'),
        ),
    ]
