# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0002_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusvisitor',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campusvisitorlog',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='campusvisitorlog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campusvisitorlog',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='security.campusvisitor'),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='guard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_passes', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='gate_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='security.gatepass'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['tenant', 'status', 'check_in_time'], name='security_ca_tenant__6ae7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['phone'], name='security_ca_phone_e07c13_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['person_to_meet', 'check_in_time'], name='security_ca_person__531a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitor',
            index=models.Index(fields=['check_in_time', 'check_out_time'], name='security_ca_check_i_df515e_idx'),
        ),
        migrations.AddIndex(
            model_name='campusvisitorlog',
            index=models.Index(fields=['tenant', 'visitor', 'timestamp'], name='security_ca_tenant__5e5904_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='security_ga_tenant__f71c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['student', 'status'], name='security_ga_student_b10169_idx'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['token'], name='security_ga_token_070716_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['tenant', 'scanned_at'], name='security_ga_tenant__7c7aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['gate_pass', 'action'], name='security_ga_gate_pa_adfa87_idx'),
        ),
    ]
