# Generated by Django 5.2.9 on 2026-01-19 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('module', models.CharField(choices=[('students', 'Students'), ('staff', 'Staff'), ('classes', 'Classes & Sections'), ('subjects', 'Subjects'), ('fee_structures', 'Fee Structures'), ('fee_allocations', 'Fee Allocations'), ('student_enrollments', 'Student Enrollments'), ('attendance', 'Attendance Records'), ('transport', 'Transport Allocations'), ('parents', 'Parent Information'), ('student_photos', 'Student Photos')], help_text='Module being imported', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('PREVIEW', 'Preview Ready'), ('IMPORTING', 'Importing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='csv, xlsx, or xls', max_length=10)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('duplicate_rows', models.IntegerField(default=0)),
                ('created_record_ids', models.JSONField(default=list, help_text='IDs of records created during import for rollback')),
                ('validation_errors', models.JSONField(default=list, help_text='List of validation errors')),
                ('preview_data', models.JSONField(default=list, help_text='Preview of data to be imported')),
                ('skip_duplicates', models.BooleanField(default=True)),
                ('update_existing', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('module', models.CharField(max_length=50)),
                ('source_column', models.CharField(help_text='Column name in CSV/Excel', max_length=100)),
                ('target_field', models.CharField(help_text='System field name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_field_mappings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Import Field Mapping',
                'verbose_name_plural': 'Import Field Mappings',
                'db_table': 'import_field_mappings',
                'unique_together': {('tenant', 'module', 'source_column')},
            },
        ),
    ]
