# Generated by Django 5.2.9 on 2026-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siblingdiscount',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Name for this discount tier (e.g., '2 Siblings Discount')", max_length=100),
        ),
    ]
