# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeadvancepayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_advance_payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='students.student'),
        ),
        migrations.AddField(
            model_name='feeallocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_allocations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeadvancepayment',
            name='fee_category',
            field=models.ForeignKey(help_text='Fee category for which advance is paid', on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feedefaulter',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_defaulter_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='feedefaulter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_defaulters', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='parent_invoice',
            field=models.ForeignKey(blank=True, help_text='Parent invoice for sibling consolidation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling_invoices', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='students.student'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='fee_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feeallocation'),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feeinvoice'),
        ),
    ]
