# Generated by Django 5.2.9 on 2026-01-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_add_name_to_sibling_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='number_of_terms',
            field=models.IntegerField(default=1, help_text='Number of terms/installments for collection (1-12)'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term_months',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for when each term fee should be collected (month numbers 1-12)'),
        ),
    ]
