# Generated by Django 5.2.9 on 2026-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feestructure_number_of_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='annual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total annual fee amount (sum of all installments)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='installment_amounts',
            field=models.JSONField(blank=True, default=dict, help_text='Custom amounts for each installment (allows unequal distribution)'),
        ),
    ]
