# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0003_initial'),
        ('students', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feerefund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_refund_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feerefund',
            name='fee_category',
            field=models.ForeignKey(help_text='Fee category being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feerefund',
            name='invoice_item',
            field=models.ForeignKey(blank=True, help_text='Specific fee item being refunded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feeinvoiceitem'),
        ),
        migrations.AddField(
            model_name='feerefund',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feerefund',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='students.student'),
        ),
        migrations.AddField(
            model_name='feerefund',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='fees.feecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feeallocation',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Null for advance payments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feerefund',
            name='original_transaction',
            field=models.ForeignKey(blank=True, help_text='Original transaction being refunded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feetransaction'),
        ),
        migrations.AddField(
            model_name='feeadvancepayment',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Original transaction that created this advance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='fees.feetransaction'),
        ),
        migrations.AddField(
            model_name='feetransactionitem',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='fees.feeinvoiceitem'),
        ),
        migrations.AddField(
            model_name='feetransactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feetransaction'),
        ),
        migrations.AddField(
            model_name='siblingdiscount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_discounts', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='feecategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='feedefaulter',
            unique_together={('tenant', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='feeallocation',
            unique_together={('student', 'fee_structure')},
        ),
        migrations.AlterUniqueTogether(
            name='siblingdiscount',
            unique_together={('tenant', 'sibling_count')},
        ),
    ]
