# Generated by Django 5.2.9 on 2026-01-13 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_feestructure_annual_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeallocation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedefaulter',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siblingdiscount',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
