# Generated by Django 5.2.9 on 2026-01-14 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feeallocation_deleted_by_feecategory_deleted_by_and_more'),
        ('students', '0010_alumnidonation_deleted_by_alumnievent_deleted_by_and_more'),
        ('tenants', '0008_add_audit_log_and_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining balance for this fee item', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoiceitem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for this specific fee item', max_digits=10),
        ),
        migrations.CreateModel(
            name='FeeAdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original advance amount', max_digits=10)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount already applied to invoices', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, help_text='Remaining advance balance', max_digits=10)),
                ('advance_for_months', models.IntegerField(default=1, help_text='Number of months this advance covers')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_USED', 'Partially Used'), ('FULLY_USED', 'Fully Used'), ('REFUNDED', 'Refunded')], default='AVAILABLE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(help_text='Fee category for which advance is paid', on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='fees.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_advance_payments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_advance_payments', to='tenants.tenant')),
                ('transaction', models.ForeignKey(blank=True, help_text='Original transaction that created this advance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='fees.feetransaction')),
            ],
            options={
                'verbose_name': 'Fee Advance Payment',
                'verbose_name_plural': 'Fee Advance Payments',
                'db_table': 'fee_advance_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('refund_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('ADJUSTMENT', 'Adjusted to Future Fees'), ('OTHER', 'Other')], max_length=20)),
                ('refund_reference', models.CharField(blank=True, help_text='Cheque number, Bank reference, etc.', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_refund_approvals', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(help_text='Fee category being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feecategory')),
                ('invoice_item', models.ForeignKey(blank=True, help_text='Specific fee item being refunded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feeinvoiceitem')),
                ('original_transaction', models.ForeignKey(blank=True, help_text='Original transaction being refunded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feetransaction')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_refund_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_refunds', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fee Refund',
                'verbose_name_plural': 'Fee Refunds',
                'db_table': 'fee_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeTransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this fee category in this transaction', max_digits=10)),
                ('is_advance', models.BooleanField(default=False, help_text='Whether this is an advance payment')),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='fees.feeinvoiceitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feetransaction')),
            ],
            options={
                'verbose_name': 'Fee Transaction Item',
                'verbose_name_plural': 'Fee Transaction Items',
                'db_table': 'fee_transaction_items',
            },
        ),
    ]
