# Generated by Django 5.2.9 on 2026-01-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_add_category_wise_payment_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Null for advance payments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fees.feeinvoice'),
        ),
    ]
