"""
Dashboard Data Seeder
Creates default widget definitions and leaderboard configurations
"""

from django.core.management.base import BaseCommand
from dashboard.models import WidgetDefinition


class Command(BaseCommand):
    help = 'Seed default widget definitions for the dashboard'

    def handle(self, *args, **options):
        self.stdout.write('Creating widget definitions...')
        
        widgets = [
            # Overview Widgets
            {
                'widget_id': 'overview_stats',
                'name': 'Overview Statistics',
                'description': 'Key metrics including students, staff, attendance, and fees',
                'component_name': 'OverviewStatsWidget',
                'category': 'system',
                'available_for_roles': ['principal', 'admin'],
                'default_width': 12,
                'default_height': 2,
                'min_width': 6,
                'min_height': 2,
                'icon': '📊',
                'is_system': True,
                'data_endpoint': '/api/dashboard/widget-data/overview_stats/',
                'refresh_interval': 300,
            },
            {
                'widget_id': 'student_count',
                'name': 'Student Count',
                'description': 'Total number of active students',
                'component_name': 'QuickStatsWidget',
                'category': 'academic',
                'available_for_roles': ['principal', 'admin', 'teacher'],
                'default_width': 3,
                'default_height': 2,
                'min_width': 2,
                'min_height': 2,
                'icon': '👨‍🎓',
                'data_endpoint': '/api/dashboard/widget-data/student_count/',
            },
            {
                'widget_id': 'staff_count',
                'name': 'Staff Count',
                'description': 'Total number of active staff members',
                'component_name': 'QuickStatsWidget',
                'category': 'hr',
                'available_for_roles': ['principal', 'admin'],
                'default_width': 3,
                'default_height': 2,
                'min_width': 2,
                'min_height': 2,
                'icon': '👨‍🏫',
                'data_endpoint': '/api/dashboard/widget-data/staff_count/',
            },
            
            # Finance Widgets
            {
                'widget_id': 'fee_trend_chart',
                'name': 'Fee Collection Trend',
                'description': 'Fee collection trend over time',
                'component_name': 'FeeTrendWidget',
                'category': 'finance',
                'available_for_roles': ['principal', 'admin', 'accountant'],
                'default_width': 6,
                'default_height': 4,
                'min_width': 4,
                'min_height': 3,
                'icon': '📈',
                'data_endpoint': '/api/dashboard/widget-data/fee_trend_chart/',
                'refresh_interval': 600,
            },
            {
                'widget_id': 'fee_overview',
                'name': 'Fee Overview',
                'description': 'Fee collection summary with pending dues',
                'component_name': 'FeeSummaryWidget',
                'category': 'finance',
                'available_for_roles': ['principal', 'admin', 'accountant'],
                'default_width': 4,
                'default_height': 3,
                'min_width': 3,
                'min_height': 2,
                'icon': '💰',
                'data_endpoint': '/api/dashboard/widget-data/fee_overview/',
            },
            {
                'widget_id': 'pending_dues',
                'name': 'Pending Dues',
                'description': 'List of students with pending fees',
                'component_name': 'FeeSummaryWidget',
                'category': 'finance',
                'available_for_roles': ['principal', 'accountant'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '⚠️',
                'data_endpoint': '/api/dashboard/widget-data/pending_dues/',
            },
            {
                'widget_id': 'recent_payments',
                'name': 'Recent Payments',
                'description': 'Latest fee payments received',
                'component_name': 'RecentActivityWidget',
                'category': 'finance',
                'available_for_roles': ['principal', 'accountant'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '💵',
                'data_endpoint': '/api/dashboard/widget-data/recent_payments/',
            },
            
            # Attendance Widgets
            {
                'widget_id': 'attendance_heatmap',
                'name': 'Attendance Heatmap',
                'description': 'Class-wise attendance heatmap',
                'component_name': 'AttendanceHeatmapWidget',
                'category': 'attendance',
                'available_for_roles': ['principal', 'admin'],
                'default_width': 8,
                'default_height': 4,
                'min_width': 6,
                'min_height': 3,
                'icon': '📅',
                'data_endpoint': '/api/dashboard/widget-data/attendance_heatmap/',
            },
            {
                'widget_id': 'attendance_summary',
                'name': 'Attendance Summary',
                'description': 'Overall attendance statistics',
                'component_name': 'AttendanceSummaryWidget',
                'category': 'attendance',
                'available_for_roles': ['principal', 'admin', 'teacher', 'parent'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '✅',
                'data_endpoint': '/api/dashboard/widget-data/attendance_summary/',
            },
            
            # Leaderboard Widgets
            {
                'widget_id': 'leaderboard_academic',
                'name': 'Academic Leaderboard',
                'description': 'Top performing students academically',
                'component_name': 'LeaderboardWidget',
                'category': 'leaderboard',
                'available_for_roles': ['principal', 'admin', 'teacher', 'student', 'parent'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '🏆',
                'data_endpoint': '/api/dashboard/widget-data/leaderboard_academic/',
            },
            {
                'widget_id': 'class_leaderboard',
                'name': 'Class Leaderboard',
                'description': 'Class rankings and performance',
                'component_name': 'LeaderboardWidget',
                'category': 'leaderboard',
                'available_for_roles': ['teacher', 'student'],
                'default_width': 6,
                'default_height': 4,
                'min_width': 4,
                'min_height': 3,
                'icon': '🥇',
                'data_endpoint': '/api/dashboard/widget-data/class_leaderboard/',
            },
            
            # Activity Widgets
            {
                'widget_id': 'recent_activity',
                'name': 'Recent Activity',
                'description': 'Latest activities and updates',
                'component_name': 'RecentActivityWidget',
                'category': 'system',
                'available_for_roles': ['principal', 'admin', 'teacher'],
                'default_width': 6,
                'default_height': 4,
                'min_width': 4,
                'min_height': 3,
                'icon': '📝',
                'data_endpoint': '/api/dashboard/widget-data/recent_activity/',
            },
            {
                'widget_id': 'upcoming_events',
                'name': 'Upcoming Events',
                'description': 'Scheduled events and reminders',
                'component_name': 'UpcomingEventsWidget',
                'category': 'communication',
                'available_for_roles': ['principal', 'admin', 'teacher', 'student', 'parent'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '📆',
                'data_endpoint': '/api/dashboard/widget-data/upcoming_events/',
            },
            {
                'widget_id': 'school_announcements',
                'name': 'Announcements',
                'description': 'Important school announcements',
                'component_name': 'AnnouncementsWidget',
                'category': 'communication',
                'available_for_roles': ['principal', 'admin', 'teacher', 'student', 'parent'],
                'default_width': 6,
                'default_height': 3,
                'min_width': 4,
                'min_height': 2,
                'icon': '📢',
                'data_endpoint': '/api/dashboard/widget-data/school_announcements/',
            },
            
            # Parent Widgets
            {
                'widget_id': 'children_overview',
                'name': 'My Children',
                'description': 'Overview of your children',
                'component_name': 'ChildrenOverviewWidget',
                'category': 'parent',
                'available_for_roles': ['parent'],
                'default_width': 12,
                'default_height': 3,
                'min_width': 6,
                'min_height': 2,
                'icon': '👨‍👩‍👧‍👦',
                'is_system': True,
                'data_endpoint': '/api/dashboard/widget-data/children_overview/',
            },
            {
                'widget_id': 'fee_summary',
                'name': 'Fee Summary',
                'description': 'Fee status for your children',
                'component_name': 'FeeSummaryWidget',
                'category': 'parent',
                'available_for_roles': ['parent'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '💳',
                'data_endpoint': '/api/dashboard/widget-data/fee_summary/',
            },
            {
                'widget_id': 'academic_progress',
                'name': 'Academic Progress',
                'description': 'Exam results and academic performance',
                'component_name': 'AcademicProgressWidget',
                'category': 'parent',
                'available_for_roles': ['parent'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '📚',
                'data_endpoint': '/api/dashboard/widget-data/academic_progress/',
            },
            {
                'widget_id': 'homework_pending',
                'name': 'Pending Homework',
                'description': 'Pending homework assignments',
                'component_name': 'HomeworkWidget',
                'category': 'parent',
                'available_for_roles': ['parent', 'student'],
                'default_width': 6,
                'default_height': 4,
                'min_width': 4,
                'min_height': 3,
                'icon': '📝',
                'data_endpoint': '/api/dashboard/widget-data/homework_pending/',
            },
            {
                'widget_id': 'recent_remarks',
                'name': 'Recent Remarks',
                'description': 'Teacher remarks and feedback',
                'component_name': 'RecentActivityWidget',
                'category': 'parent',
                'available_for_roles': ['parent'],
                'default_width': 6,
                'default_height': 4,
                'min_width': 4,
                'min_height': 3,
                'icon': '💬',
                'data_endpoint': '/api/dashboard/widget-data/recent_remarks/',
            },
            
            # Teacher Widgets
            {
                'widget_id': 'my_classes_today',
                'name': "Today's Classes",
                'description': 'Your scheduled classes for today',
                'component_name': 'TimetableWidget',
                'category': 'teacher',
                'available_for_roles': ['teacher'],
                'default_width': 4,
                'default_height': 3,
                'min_width': 3,
                'min_height': 2,
                'icon': '🎓',
                'data_endpoint': '/api/dashboard/widget-data/my_classes_today/',
            },
            {
                'widget_id': 'pending_tasks',
                'name': 'Pending Tasks',
                'description': 'Tasks assigned to you',
                'component_name': 'PendingTasksWidget',
                'category': 'teacher',
                'available_for_roles': ['teacher'],
                'default_width': 4,
                'default_height': 4,
                'min_width': 3,
                'min_height': 3,
                'icon': '✓',
                'data_endpoint': '/api/dashboard/widget-data/pending_tasks/',
            },
            {
                'widget_id': 'homework_status',
                'name': 'Homework Status',
                'description': 'Submission status of assigned homework',
                'component_name': 'HomeworkWidget',
                'category': 'teacher',
                'available_for_roles': ['teacher'],
                'default_width': 6,
                'default_height': 4,
                'min_width': 4,
                'min_height': 3,
                'icon': '📋',
                'data_endpoint': '/api/dashboard/widget-data/homework_status/',
            },
            
            # Student Widgets
            {
                'widget_id': 'my_schedule_today',
                'name': "Today's Schedule",
                'description': 'Your class schedule for today',
                'component_name': 'TimetableWidget',
                'category': 'student',
                'available_for_roles': ['student'],
                'default_width': 6,
                'default_height': 3,
                'min_width': 4,
                'min_height': 2,
                'icon': '📅',
                'data_endpoint': '/api/dashboard/widget-data/my_schedule_today/',
            },
            {
                'widget_id': 'my_attendance',
                'name': 'My Attendance',
                'description': 'Your attendance summary',
                'component_name': 'AttendanceSummaryWidget',
                'category': 'student',
                'available_for_roles': ['student'],
                'default_width': 3,
                'default_height': 3,
                'min_width': 2,
                'min_height': 2,
                'icon': '✅',
                'data_endpoint': '/api/dashboard/widget-data/my_attendance/',
            },
            {
                'widget_id': 'my_rank',
                'name': 'My Rank',
                'description': 'Your current class rank',
                'component_name': 'LeaderboardWidget',
                'category': 'student',
                'available_for_roles': ['student'],
                'default_width': 3,
                'default_height': 3,
                'min_width': 2,
                'min_height': 2,
                'icon': '🏅',
                'data_endpoint': '/api/dashboard/widget-data/my_rank/',
            },
            {
                'widget_id': 'recent_results',
                'name': 'Recent Results',
                'description': 'Your recent exam results',
                'component_name': 'AcademicProgressWidget',
                'category': 'student',
                'available_for_roles': ['student'],
                'default_width': 6,
                'default_height': 3,
                'min_width': 4,
                'min_height': 2,
                'icon': '📊',
                'data_endpoint': '/api/dashboard/widget-data/recent_results/',
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for widget_data in widgets:
            obj, created = WidgetDefinition.objects.update_or_create(
                widget_id=widget_data['widget_id'],
                defaults=widget_data
            )
            if created:
                created_count += 1
            else:
                updated_count += 1
        
        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully seeded {created_count} new widgets and updated {updated_count} existing widgets'
            )
        )
