# Generated by Django 5.1.4 on 2025-12-30 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('tenants', '0003_department_gradelevel_section_subject_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PAID', 'Paid')], default='DRAFT', help_text='Payroll cycle status', max_length=20)),
                ('processed_on', models.DateTimeField(blank=True, help_text='When payroll was processed', null=True)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, help_text='Total gross salary', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions', max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=0.0, help_text='Total net salary', max_digits=12)),
                ('remarks', models.TextField(blank=True, help_text='Remarks or notes')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Who processed the payroll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Cycle',
                'verbose_name_plural': 'Payroll Cycles',
                'db_table': 'payroll_cycles',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('total_working_days', models.IntegerField(help_text='Total working days in month')),
                ('days_present', models.DecimalField(decimal_places=1, help_text='Days present', max_digits=5)),
                ('days_absent', models.DecimalField(decimal_places=1, default=0.0, help_text='Days absent (unpaid)', max_digits=5)),
                ('paid_leaves', models.DecimalField(decimal_places=1, default=0.0, help_text='Paid leave days', max_digits=5)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary', max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Gross salary (before deductions)', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions', max_digits=10)),
                ('loss_of_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Loss of pay for absences', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Net salary (after deductions)', max_digits=10)),
                ('payslip_pdf', models.FileField(blank=True, help_text='Generated payslip PDF', null=True, upload_to='payslips/%Y/%m/')),
                ('remarks', models.TextField(blank=True, help_text='Remarks or notes')),
                ('payroll_cycle', models.ForeignKey(help_text='Payroll cycle', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollcycle')),
                ('staff', models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'db_table': 'payslips',
                'ordering': ['-payroll_cycle__year', '-payroll_cycle__month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Component name (e.g., HRA, Transport)', max_length=100)),
                ('code', models.CharField(help_text='Short code (e.g., HRA, TA)', max_length=20)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], help_text='Earning or Deduction', max_length=10)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Base')], help_text='How to calculate this component', max_length=10)),
                ('default_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Default value (amount or percentage)', max_digits=10)),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether this component is taxable')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this component is active')),
                ('description', models.TextField(blank=True, help_text='Component description')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'db_table': 'salary_components',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Component amount', max_digits=10)),
                ('payslip', models.ForeignKey(help_text='Payslip', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payslip')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('component', models.ForeignKey(help_text='Salary component', on_delete=django.db.models.deletion.CASCADE, related_name='payslip_components', to='payroll.salarycomponent')),
            ],
            options={
                'verbose_name': 'Payslip Component',
                'verbose_name_plural': 'Payslip Components',
                'db_table': 'payslip_components',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('effective_from', models.DateField(help_text='Effective from date')),
                ('effective_to', models.DateField(blank=True, help_text='Effective to date (null if current)', null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this structure is active')),
                ('remarks', models.TextField(blank=True, help_text='Remarks or notes')),
                ('staff', models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='staff.staff')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'db_table': 'salary_structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_structure',
            field=models.ForeignKey(help_text='Salary structure used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.salarystructure'),
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Component value (amount or percentage)', max_digits=10)),
                ('component', models.ForeignKey(help_text='Salary component', on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='payroll.salarycomponent')),
                ('salary_structure', models.ForeignKey(help_text='Salary structure', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Salary Structure Component',
                'verbose_name_plural': 'Salary Structure Components',
                'db_table': 'salary_structure_components',
            },
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['tenant', 'year', 'month'], name='payroll_cyc_tenant__f0d7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['status'], name='payroll_cyc_status_a6df63_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollcycle',
            constraint=models.UniqueConstraint(fields=('tenant', 'month', 'year'), name='unique_payroll_cycle'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['tenant', 'is_active'], name='salary_comp_tenant__61ffc1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['tenant', 'staff', 'is_active'], name='salary_stru_tenant__412d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['effective_from', 'effective_to'], name='salary_stru_effecti_2ca60f_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'staff'], name='payslips_tenant__05df2e_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll_cycle'], name='payslips_payroll_ca4d7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_cycle', 'staff'), name='unique_payslip'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'component'), name='unique_structure_component'),
        ),
    ]
