# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcycle',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Who processed the payroll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to='staff.staff'),
        ),
    ]
