# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0002_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcycle',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_cycle',
            field=models.ForeignKey(help_text='Payroll cycle', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollcycle'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payslipcomponent',
            name='payslip',
            field=models.ForeignKey(help_text='Payslip', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payslip'),
        ),
        migrations.AddField(
            model_name='payslipcomponent',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payslipcomponent',
            name='component',
            field=models.ForeignKey(help_text='Salary component', on_delete=django.db.models.deletion.CASCADE, related_name='payslip_components', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='staff',
            field=models.ForeignKey(help_text='Staff member', on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary_structure',
            field=models.ForeignKey(help_text='Salary structure used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='component',
            field=models.ForeignKey(help_text='Salary component', on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='payroll.salarycomponent'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='salary_structure',
            field=models.ForeignKey(help_text='Salary structure', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructure'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['tenant', 'year', 'month'], name='payroll_cyc_tenant__f0d7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcycle',
            index=models.Index(fields=['status'], name='payroll_cyc_status_a6df63_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollcycle',
            constraint=models.UniqueConstraint(fields=('tenant', 'month', 'year'), name='unique_payroll_cycle'),
        ),
        migrations.AddIndex(
            model_name='salarycomponent',
            index=models.Index(fields=['tenant', 'is_active'], name='salary_comp_tenant__61ffc1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['tenant', 'staff', 'is_active'], name='salary_stru_tenant__412d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['effective_from', 'effective_to'], name='salary_stru_effecti_2ca60f_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'staff'], name='payslips_tenant__05df2e_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll_cycle'], name='payslips_payroll_ca4d7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_cycle', 'staff'), name='unique_payslip'),
        ),
        migrations.AddConstraint(
            model_name='salarystructurecomponent',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'component'), name='unique_structure_component'),
        ),
    ]
