# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to user account for login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffappraisal',
            name='appraisal_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='staff.appraisalcycle'),
        ),
        migrations.AddField(
            model_name='staffappraisal',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appraisals', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffappraisal',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffappraisal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_appraisals', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_staff_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_staff_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffgoal',
            name='appraisal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='staff.staffappraisal'),
        ),
        migrations.AddField(
            model_name='staffgoal',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffgoal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_goals', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffhealthprofile',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffhealthprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_health_profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffinjuryreport',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_reports', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffinjuryreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_injury_reports', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leaves', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffmedicalcheckup',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkups', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffmedicalcheckup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_medical_checkups', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffmedicalhistory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffmedicalhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_medical_history', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='staffvaccination',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='staffvaccination',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_vaccinations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='staff.trainingenrollment'),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_feedbacks', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='training_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='staff.trainingprogram'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('tenant', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='staffappraisal',
            unique_together={('appraisal_cycle', 'staff')},
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingenrollment',
            unique_together={('training_program', 'staff')},
        ),
    ]
