# Generated by Django 5.2.9 on 2026-09-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='manual_qr_code',
            field=models.CharField(blank=True, db_index=True, help_text='Manually assigned/external QR code text. Resolves to this staff member in addition to the system-generated QR.', max_length=255, null=True, unique=True),
        ),
    ]
