# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_studentfaceencoding'),
        ('staff', '0002_staffattendance_biometric_device_id_and_more'),
        ('students', '0008_historicalstudent_caste_and_more'),
        ('tenants', '0007_add_receipt_config_to_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardGenerationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied (class, section, etc.)')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=10)),
                ('layout', models.CharField(choices=[('individual', 'Individual Files'), ('grid', 'Grid Layout (9 per A4)'), ('sheet', 'Print Sheet')], default='individual', max_length=20)),
                ('include_qr', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_cards', models.IntegerField(default=0)),
                ('completed_cards', models.IntegerField(default=0)),
                ('failed_cards', models.IntegerField(default=0)),
                ('download_url', models.URLField(blank=True, max_length=500, null=True)),
                ('individual_files', models.JSONField(default=list, help_text='List of individual file URLs')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Generation Job',
                'verbose_name_plural': 'ID Card Generation Jobs',
                'db_table': 'idcard_generation_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('entity_id', models.UUIDField(help_text='Student or Staff ID')),
                ('file_url', models.URLField(help_text='URL to generated PDF/PNG', max_length=500)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('replaced', 'Replaced'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='Card expiry date')),
                ('printed_count', models.IntegerField(default=0)),
                ('last_printed', models.DateTimeField(blank=True, null=True)),
                ('bulk_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cards', to='idcards.idcardgenerationjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Record',
                'verbose_name_plural': 'ID Card Records',
                'db_table': 'idcard_records',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='IDCardQRCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('entity_id', models.UUIDField(help_text='Student or Staff ID')),
                ('qr_data', models.TextField(help_text='Encrypted JSON payload')),
                ('qr_hash', models.CharField(db_index=True, help_text='SHA-256 hash for quick lookup', max_length=64, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='QR code expiry date')),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_qr_codes', to='tenants.tenant')),
                ('id_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='idcards.idcardrecord')),
            ],
            options={
                'verbose_name': 'ID Card QR Code',
                'verbose_name_plural': 'ID Card QR Codes',
                'db_table': 'idcard_qr_codes',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], help_text='Entity type this template is for', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Card orientation', max_length=10)),
                ('width', models.FloatField(default=54.0, help_text='Card width in mm', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('height', models.FloatField(default=86.0, help_text='Card height in mm', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('config', models.JSONField(default=dict, help_text='Template configuration with elements, styling, etc.')),
                ('background_type', models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='color', max_length=20)),
                ('background_value', models.TextField(blank=True, help_text='Background color hex, gradient JSON, or image URL')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this entity type')),
                ('is_system', models.BooleanField(default=False, help_text='System pre-loaded template (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions', to='idcards.idcardtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcard_templates_v2', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
                'db_table': 'idcard_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='idcardrecord',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_cards', to='idcards.idcardtemplate'),
        ),
        migrations.AddField(
            model_name='idcardgenerationjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='idcards.idcardtemplate'),
        ),
        migrations.CreateModel(
            name='QRAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_timestamp', models.DateTimeField(db_index=True)),
                ('scan_location', models.CharField(blank=True, max_length=100)),
                ('scan_device', models.CharField(blank=True, max_length=100)),
                ('scan_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=10)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('early_departure', 'Early Departure')], default='present', max_length=20)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_valid_scan', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('linked_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='attendance.attendancerecord')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='idcards.idcardqrcode')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance', to='staff.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'QR Attendance Record',
                'verbose_name_plural': 'QR Attendance Records',
                'db_table': 'qr_attendance',
                'ordering': ['-scan_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='idcardqrcode',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='idcard_qr_c_tenant__3da1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardqrcode',
            index=models.Index(fields=['qr_hash'], name='idcard_qr_c_qr_hash_b3b27d_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardqrcode',
            index=models.Index(fields=['is_active', 'valid_until'], name='idcard_qr_c_is_acti_29a118_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardtemplate',
            index=models.Index(fields=['tenant', 'entity_type', 'is_active'], name='idcard_temp_tenant__2161c7_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardtemplate',
            index=models.Index(fields=['is_system', 'entity_type'], name='idcard_temp_is_syst_605d4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='idcardtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'entity_type', 'is_default'), name='unique_default_template_per_entity'),
        ),
        migrations.AddIndex(
            model_name='idcardrecord',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='idcard_reco_tenant__0abc01_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardrecord',
            index=models.Index(fields=['status', 'valid_until'], name='idcard_reco_status_e49a11_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardrecord',
            index=models.Index(fields=['bulk_job'], name='idcard_reco_bulk_jo_29d691_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgenerationjob',
            index=models.Index(fields=['tenant', 'status'], name='idcard_gene_tenant__fa8787_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgenerationjob',
            index=models.Index(fields=['celery_task_id'], name='idcard_gene_celery__05a509_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgenerationjob',
            index=models.Index(fields=['-created_at'], name='idcard_gene_created_e69b69_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['tenant', 'scan_timestamp'], name='qr_attendan_tenant__b756ab_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['student', 'scan_timestamp'], name='qr_attendan_student_9f6b50_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['staff', 'scan_timestamp'], name='qr_attendan_staff_i_76e026_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['qr_code', '-scan_timestamp'], name='qr_attendan_qr_code_162cc3_idx'),
        ),
    ]
