# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardGenerationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied (class, section, etc.)')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=10)),
                ('layout', models.CharField(choices=[('individual', 'Individual Files'), ('grid', 'Grid Layout (9 per A4)'), ('sheet', 'Print Sheet')], default='individual', max_length=20)),
                ('include_qr', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_cards', models.IntegerField(default=0)),
                ('completed_cards', models.IntegerField(default=0)),
                ('failed_cards', models.IntegerField(default=0)),
                ('download_url', models.URLField(blank=True, max_length=500, null=True)),
                ('individual_files', models.JSONField(default=list, help_text='List of individual file URLs')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'ID Card Generation Job',
                'verbose_name_plural': 'ID Card Generation Jobs',
                'db_table': 'idcard_generation_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardQRCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('entity_id', models.UUIDField(help_text='Student or Staff ID')),
                ('qr_data', models.TextField(help_text='Encrypted JSON payload')),
                ('qr_hash', models.CharField(db_index=True, help_text='SHA-256 hash for quick lookup', max_length=64, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='QR code expiry date')),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ID Card QR Code',
                'verbose_name_plural': 'ID Card QR Codes',
                'db_table': 'idcard_qr_codes',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='IDCardRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('entity_id', models.UUIDField(help_text='Student or Staff ID')),
                ('file_url', models.URLField(help_text='URL to generated PDF/PNG', max_length=500)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpg', 'JPG')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('replaced', 'Replaced'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='Card expiry date')),
                ('printed_count', models.IntegerField(default=0)),
                ('last_printed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ID Card Record',
                'verbose_name_plural': 'ID Card Records',
                'db_table': 'idcard_records',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], help_text='Entity type this template is for', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Card orientation', max_length=10)),
                ('width', models.FloatField(default=54.0, help_text='Card width in mm', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('height', models.FloatField(default=86.0, help_text='Card height in mm', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('config', models.JSONField(default=dict, help_text='Template configuration with elements, styling, etc.')),
                ('background_type', models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='color', max_length=20)),
                ('background_value', models.TextField(blank=True, help_text='Background color hex, gradient JSON, or image URL')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this entity type')),
                ('is_system', models.BooleanField(default=False, help_text='System pre-loaded template (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
                'db_table': 'idcard_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_timestamp', models.DateTimeField(db_index=True)),
                ('scan_location', models.CharField(blank=True, max_length=100)),
                ('scan_device', models.CharField(blank=True, max_length=100)),
                ('scan_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], default='entry', max_length=10)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('early_departure', 'Early Departure')], default='present', max_length=20)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_valid_scan', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'QR Attendance Record',
                'verbose_name_plural': 'QR Attendance Records',
                'db_table': 'qr_attendance',
                'ordering': ['-scan_timestamp'],
            },
        ),
    ]
