# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0003_initial'),
        ('idcards', '0001_initial'),
        ('staff', '0002_initial'),
        ('students', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardgenerationjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idcardgenerationjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_jobs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='idcardqrcode',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_qr_codes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='idcardrecord',
            name='bulk_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='idcards.idcardgenerationjob'),
        ),
        migrations.AddField(
            model_name='idcardrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='idcardqrcode',
            name='id_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='idcards.idcardrecord'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions', to='idcards.idcardtemplate'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcard_templates_v2', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='idcardrecord',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_cards', to='idcards.idcardtemplate'),
        ),
        migrations.AddField(
            model_name='idcardgenerationjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='idcards.idcardtemplate'),
        ),
        migrations.AddField(
            model_name='qrattendance',
            name='linked_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='qrattendance',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='idcards.idcardqrcode'),
        ),
        migrations.AddField(
            model_name='qrattendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='qrattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance', to='students.student'),
        ),
        migrations.AddField(
            model_name='qrattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_records', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='idcardqrcode',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='idcard_qr_c_tenant__3da1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardqrcode',
            index=models.Index(fields=['qr_hash'], name='idcard_qr_c_qr_hash_b3b27d_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardqrcode',
            index=models.Index(fields=['is_active', 'valid_until'], name='idcard_qr_c_is_acti_29a118_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardtemplate',
            index=models.Index(fields=['tenant', 'entity_type', 'is_active'], name='idcard_temp_tenant__2161c7_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardtemplate',
            index=models.Index(fields=['is_system', 'entity_type'], name='idcard_temp_is_syst_605d4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='idcardtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'entity_type', 'is_default'), name='unique_default_template_per_entity'),
        ),
        migrations.AddIndex(
            model_name='idcardrecord',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='idcard_reco_tenant__0abc01_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardrecord',
            index=models.Index(fields=['status', 'valid_until'], name='idcard_reco_status_e49a11_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardrecord',
            index=models.Index(fields=['bulk_job'], name='idcard_reco_bulk_jo_29d691_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgenerationjob',
            index=models.Index(fields=['tenant', 'status'], name='idcard_gene_tenant__fa8787_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgenerationjob',
            index=models.Index(fields=['celery_task_id'], name='idcard_gene_celery__05a509_idx'),
        ),
        migrations.AddIndex(
            model_name='idcardgenerationjob',
            index=models.Index(fields=['-created_at'], name='idcard_gene_created_e69b69_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['tenant', 'scan_timestamp'], name='qr_attendan_tenant__b756ab_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['student', 'scan_timestamp'], name='qr_attendan_student_9f6b50_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['staff', 'scan_timestamp'], name='qr_attendan_staff_i_76e026_idx'),
        ),
        migrations.AddIndex(
            model_name='qrattendance',
            index=models.Index(fields=['qr_code', '-scan_timestamp'], name='qr_attendan_qr_code_162cc3_idx'),
        ),
    ]
