# Generated by Django 5.2.9 on 2026-01-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcardrecord',
            name='bulk_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='idcards.idcardgenerationjob'),
        ),
    ]
