# Generated by Django 5.2.9 on 2026-09-10 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendance',
            name='resolution_source',
            field=models.CharField(blank=True, default='generated', help_text='How the scanned QR text was resolved to an entity', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrattendance',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='idcards.idcardqrcode'),
        ),
    ]
