# Generated by Django 5.2.9 on 2026-01-04 01:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        ('staff', '0002_staffattendance_biometric_device_id_and_more'),
        ('tenants', '0005_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpdeskticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Helpdesk Ticket', 'verbose_name_plural': 'Helpdesk Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='category',
            field=models.CharField(choices=[('FEE', 'Fee Issue'), ('ACADEMIC', 'Academic Query'), ('TRANSPORT', 'Transport Issue'), ('IT', 'Platform/Tech Support'), ('HOSTEL', 'Hostel Issue'), ('LIBRARY', 'Library Issue'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='helpdesk_ti_tenant__b66643_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['assigned_to', 'status'], name='helpdesk_ti_assigne_7efd70_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['raised_by', 'status'], name='helpdesk_ti_raised__32e15f_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['category', 'priority'], name='helpdesk_ti_categor_7c0b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['tenant', 'ticket', 'created_at'], name='helpdesk_co_tenant__f8a413_idx'),
        ),
    ]
