# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesk', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskticket',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.helpdeskticket'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='helpdesk_ti_tenant__b66643_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['assigned_to', 'status'], name='helpdesk_ti_assigne_7efd70_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['raised_by', 'status'], name='helpdesk_ti_raised__32e15f_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskticket',
            index=models.Index(fields=['category', 'priority'], name='helpdesk_ti_categor_7c0b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['tenant', 'ticket', 'created_at'], name='helpdesk_co_tenant__f8a413_idx'),
        ),
    ]
