# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('email', models.EmailField(db_index=True, help_text='Globally unique email address', max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('avatar_url', models.URLField(blank=True, help_text='URL to user avatar image', max_length=500)),
                ('is_2fa_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user')),
                ('totp_secret', models.CharField(blank=True, help_text='TOTP secret for 2FA', max_length=32)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('is_platform_admin', models.BooleanField(db_index=True, default=False, help_text='Platform super admin (can manage all tenants)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this user belongs to (null for platform super admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='UI theme preference', max_length=10)),
                ('density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable')], default='comfortable', help_text='UI density preference', max_length=15)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('ur', 'Urdu')], db_index=True, default='en', help_text='Preferred language', max_length=5)),
                ('notification_channels', models.JSONField(default=dict, help_text='Notification channel preferences (e.g., {"sms": true, "email": false, "whatsapp": true})')),
                ('sidebar_collapsed', models.BooleanField(default=False, help_text='Whether sidebar is collapsed by default')),
                ('dashboard_widgets', models.JSONField(default=list, help_text='Dashboard widget configuration (order and visibility)')),
                ('timezone', models.CharField(default='UTC', help_text='User timezone', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', help_text='Preferred date format', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='24h', help_text='Preferred time format', max_length=10)),
                ('font_family', models.CharField(default='Inter, sans-serif', help_text='Preferred font family (e.g., Inter, Roboto, Poppins)', max_length=100)),
                ('font_size', models.CharField(choices=[('small', 'Small (14px)'), ('medium', 'Medium (16px)'), ('large', 'Large (18px)'), ('extra-large', 'Extra Large (20px)')], default='medium', help_text='Preferred font size', max_length=20)),
                ('font_color', models.CharField(default='#1a1a1a', help_text='Custom text color in hex format (e.g., #1a1a1a)', max_length=7)),
                ('heading_color', models.CharField(default='#1a1a1a', help_text='Custom heading color in hex format (e.g., #1a1a1a)', max_length=7)),
                ('link_color', models.CharField(default='#0066cc', help_text='Custom link color in hex format (e.g., #0066cc)', max_length=7)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When impersonation started')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When impersonation ended', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the impersonator')),
                ('reason', models.TextField(help_text='Reason for impersonation')),
                ('impersonated_user', models.ForeignKey(help_text='User who was impersonated', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
                ('impersonator', models.ForeignKey(help_text='Platform admin who performed the impersonation', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant context of the impersonation', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'db_table': 'impersonation_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('resource', models.CharField(db_index=True, help_text='Resource/module name (e.g., student_module, fee_module)', max_length=100)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import')], db_index=True, help_text='Action that can be performed', max_length=20)),
                ('code', models.SlugField(help_text='Unique permission code (e.g., student_module.create)', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Permission description')),
                ('group', models.CharField(blank=True, db_index=True, help_text='Permission group for UI organization (e.g., Dashboard, Website, Finance)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Human-readable display name for the permission', max_length=150)),
                ('sort_order', models.IntegerField(default=0, help_text='Sort order within group')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['group', 'sort_order', 'resource', 'action'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'action'), name='unique_resource_action')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('name', models.CharField(help_text='Role name (e.g., Principal, Teacher)', max_length=100)),
                ('code', models.SlugField(help_text='Unique role code (e.g., principal, teacher)')),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this role is active')),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When this permission was granted to the role')),
                ('permission', models.ForeignKey(help_text='Permission', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission')),
                ('role', models.ForeignKey(help_text='Role', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='roles', through='users.RolePermission', to='users.permission'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this role was assigned to the user')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='users', through='users.UserRole', to='users.role'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_role_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'email'], name='users_tenant__afadfd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'is_active'], name='users_tenant__2f74ee_idx'),
        ),
    ]
