# Generated by Django 5.2.9 on 2026-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['group', 'sort_order', 'resource', 'action'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AddField(
            model_name='permission',
            name='display_name',
            field=models.CharField(blank=True, help_text='Human-readable display name for the permission', max_length=150),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.CharField(blank=True, db_index=True, help_text='Permission group for UI organization (e.g., Dashboard, Website, Finance)', max_length=100),
        ),
        migrations.AddField(
            model_name='permission',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Sort order within group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='users', through='users.UserRole', through_fields=('user', 'role'), to='users.role'),
        ),
    ]
