# Generated by Django 5.1.4 on 2026-09-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginactivitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginactivitylog',
            new_name='login_activ_tenant__c754b4_idx',
            old_name='login_activ_tenant__f80dd4_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivitylog',
            new_name='login_activ_user_id_aaaf4b_idx',
            old_name='login_activ_user_id_b8b119_idx',
        ),
        migrations.RenameIndex(
            model_name='loginactivitylog',
            new_name='login_activ_ip_addr_3141f3_idx',
            old_name='login_activ_ip_addr_4dd9f2_idx',
        ),
    ]
