# Generated by Django 5.2.9 on 2026-01-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_font_customization'),
        ('users', '0003_add_font_customization'),
    ]

    operations = [
    ]
