# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, help_text='UUID of user who deleted this record', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('RESTORE', 'Restore'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('module', models.CharField(db_index=True, help_text='Module/app where action occurred (e.g., students, fees)', max_length=50)),
                ('resource', models.CharField(help_text='Type of resource affected (e.g., Student, FeeStructure)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent string')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Details of changes made (old/new values)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', help_text='Outcome of the action', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
