# Generated by Django 5.2.9 on 2026-01-12 14:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_add_audit_log_and_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('RESTORE', 'Restore'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('module', models.CharField(db_index=True, help_text='Module/app where action occurred (e.g., students, fees)', max_length=50)),
                ('resource', models.CharField(help_text='Type of resource affected (e.g., Student, FeeStructure)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent string')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Details of changes made (old/new values)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', help_text='Outcome of the action', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='audit_logs_tenant__79c676_idx'), models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['module', '-timestamp'], name='audit_logs_module_ff6746_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
