# Generated by Django 5.2.9 on 2026-01-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('staff', '0002_staffattendance_biometric_device_id_and_more'),
        ('students', '0002_studentenrollment_and_more'),
        ('tenants', '0005_tenantsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificaterequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Certificate Request', 'verbose_name_plural': 'Certificate Requests'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Certificate Template', 'verbose_name_plural': 'Certificate Templates'},
        ),
        migrations.AlterModelOptions(
            name='generatedcertificate',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Generated Certificate', 'verbose_name_plural': 'Generated Certificates'},
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['tenant', 'status', 'requested_at'], name='certificate_tenant__bdee93_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['student', 'status'], name='certificate_student_e5766f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='certificate_tenant__886e20_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcertificate',
            index=models.Index(fields=['tenant', 'certificate_number'], name='generated_c_tenant__1b5111_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcertificate',
            index=models.Index(fields=['issued_date', 'verified'], name='generated_c_issued__809ab9_idx'),
        ),
    ]
