# Generated by Django 5.1.4 on 2026-01-19 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0003_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_certificate', to='certificates.certificaterequest'),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='certificate_tenant__886e20_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['tenant', 'status', 'requested_at'], name='certificate_tenant__bdee93_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterequest',
            index=models.Index(fields=['student', 'status'], name='certificate_student_e5766f_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcertificate',
            index=models.Index(fields=['tenant', 'certificate_number'], name='generated_c_tenant__1b5111_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcertificate',
            index=models.Index(fields=['issued_date', 'verified'], name='generated_c_issued__809ab9_idx'),
        ),
    ]
